/* The whole story, in short: a short, plain answer to "What is this story about?"

   WHY THIS EXISTS
   Search engines and AI answer tools (Google AI Overviews, ChatGPT search,
   Perplexity, Copilot) quote short, direct answers. Story pages open at
   Scene 1, so there was no plain answer anywhere on the page. This text
   sits in a closed drawer at the top of the Story step ("The whole story,
   in short"), so it doesn't spoil the story for readers, and it feeds the
   FAQ data for search engines together with the Big Idea.

   HOW TO WRITE ONE (two or three sentences)
   Follow the Style Guide: short sentences, past tense for stories, present
   tense for teachings and prayers, no semicolons, names instead of "he".
   Say what happens, including the ending. Don't add anything the story page
   doesn't already say. Two or three sentences. The Big Idea is added
   automatically from the story file, so don't repeat it here.

   Every story with an entry here gets the drawer and the FAQ data. */

export const IN_SHORT: Record<string, string> = {
  "psalm-8":
    "David looks at the night sky — the moon, the stars, the work of God's fingers — and asks: \"what is man that You are mindful of him?\" The God who made galaxies could overlook anyone. But God has crowned people with glory and honor and placed all creation under their feet. Wonder leads back to worship. The psalm begins and ends the same way: O LORD, our Lord, how majestic is Your name in all the earth.",
  "psalm-15":
    "Psalm 15 asks: who may stay on God's holy mountain? The answer is a person of integrity — one who walks blamelessly, speaks truth without slander, does not take bribes, and lends money without charging interest. Such a person keeps a promise even when it costs them. These are not ways to earn God's favor; they are marks of the person formed by it. The closing line is the promise: he who does these things will never be shaken.",
  "psalm-16":
    "David prays for preservation and declares that God is his only true good: \"You are my Lord; apart from You I have no good thing.\" The LORD is his chosen portion and inheritance, better than any plot of ground. With God always before him, David will not be shaken. Even his body will rest securely, because God will not abandon his soul to Sheol or let his Holy One see decay. The path of life goes through God's presence — with joy that does not end.",
  "psalm-19":
    "The heavens declare the glory of God without speaking a word — their voice goes out to all the earth. Then the psalm turns to God's law, which is more desirable than gold and sweeter than honey. David asks God to cleanse him from hidden faults and keep him from presumptuous sins. He closes with the most prayed verse in the Psalter: \"May the words of my mouth and the meditation of my heart be acceptable in Your sight, O LORD, my Rock and my Redeemer.\"",
  "psalm-22":
    "Psalm 22 begins with the darkest cry in the Psalms: \"My God, my God, why have You forsaken me?\" — the words Jesus prayed from the cross. The writer is mocked, surrounded, poured out like water, with bones disjointed and hands and feet pierced. Yet he says God has not hidden his face: he attended to the cry for help. The psalm ends with all the ends of the earth turning to the LORD, proclaiming all that he has done.",
  "psalm-34":
    "Psalm 34 is an alphabet acrostic of praise. David begins: \"I will bless the LORD at all times; His praise will always be on my lips.\" He calls the humble to rejoice with him: \"Taste and see that the LORD is good.\" The angel of the LORD camps around those who fear him. The LORD is close to the brokenhearted and saves those crushed in spirit. Many are the afflictions of the righteous, but the LORD delivers from them all, and those who take refuge in him are never condemned.",
  "psalm-80":
    "Psalm 80 is a national lament. God planted Israel like a vine from Egypt, cleared the land for it, and let it fill the mountains — but now its walls are broken down and its fruit is picked by strangers. Three times the prayer rises, each time with a fuller name: Restore us, O God; O God of Hosts; O LORD God of Hosts — cause Your face to shine upon us, that we may be saved. The son of man at God's right hand is the hope for the answer.",
  "psalm-85":
    "The people of God have been restored before and ask to be restored again: \"Will You not revive us again, that Your people may rejoice in You?\" The psalmist pauses to listen for what God will say. The answer: loving devotion and faithfulness have joined together; righteousness and peace have kissed. Faithfulness sprouts from the earth and righteousness looks down from heaven. Where those four meet is the gospel — the cross is where God's justice and mercy both are fully satisfied.",
  "psalm-92":
    "Psalm 92 is the only psalm headed \"A song for the Sabbath day.\" It is good to praise the LORD in the morning and declare his faithfulness at night, for his works are great and his thoughts run deep. The wicked may flourish like grass, but they will be destroyed — the LORD is exalted forever. The righteous flourish like a palm tree, planted in the house of the LORD. In old age they will still bear fruit, proclaiming: \"The LORD is upright; He is my Rock, and in Him there is no unrighteousness.\"",
  "psalm-104":
    "Psalm 104 is a sweeping tour of creation: God wrapped in light as a garment, the heavens stretched out like a tent, waters set in their place, springs in the valleys, grass for cattle, wine that gladdens the heart of man, trees for birds, lions hunting at night, and Leviathan — the great sea creature — made to frolic. All creatures look to God to open his hand and satisfy them. When he sends his Spirit, they are created, and the face of the earth is renewed.",
  "psalm-138":
    "David gives wholehearted thanks before the nations: \"On the day I called, You answered me; You emboldened me and strengthened my soul.\" Though God is high, he attends to the lowly, while the proud he sees only from a distance. If David walks through trouble, God extends his hand. He ends with confidence: \"The LORD will fulfill His purpose for me. O LORD, Your loving devotion endures forever — do not abandon the works of Your hands.\" God finishes what he begins.",
  "psalm-146":
    "Psalm 146 opens and closes with Hallelujah, and in between it says: do not put your trust in princes — when they die, their plans die with them. Trust the God of Jacob, who made everything and remains faithful forever. He executes justice for the oppressed, feeds the hungry, frees prisoners, opens blind eyes, lifts those who are bowed down, and protects foreigners, orphans, and widows. Princes die; the LORD reigns forever.",
  "psalm-1":
    "Psalm 1 says the truly happy person doesn't follow the advice of the wicked, but delights in God's teaching and thinks on it day and night. That person is like a tree planted by streams of water, bearing fruit, with leaves that don't wither. People who ignore God are like chaff the wind blows away. The LORD watches over the way of the righteous.",
  "psalm-25":
    "David lifts his soul to God and trusts him. He prays, \"Show me Your ways, O LORD; teach me Your paths,\" and asks God to remember his love and forget the sins of his youth. Because God is good, he shows sinners the way. Lonely and in trouble, David asks God to turn to him, forgive him, and guard his life.",
  "psalm-29":
    "David calls even the heavenly beings to give God glory. Then he describes a thunderstorm: the voice of the LORD thunders over the waters, breaks the cedars of Lebanon, flashes with fire, and shakes the wilderness, while everyone in his temple cries, \"Glory!\" The LORD sits enthroned over the flood as King forever, and he gives his people strength and peace.",
  "psalm-30":
    "David praises God for lifting him up: \"I cried to You for help, and You healed me.\" God's anger lasts a moment, but his favor lasts a lifetime. \"Weeping may stay the night, but joy comes in the morning.\" When God hid his face, David begged for mercy, and God turned his mourning into dancing and clothed him with joy.",
  "psalm-31":
    "David takes refuge in God, his rock and fortress, and prays, \"Into Your hands I commit my spirit.\" He is worn out with grief, avoided by friends, forgotten like a broken jar, with terror on every side. But he says, \"I trust in You, O LORD; My times are in Your hands.\" Jesus prayed this psalm's words as he died on the cross.",
  "psalm-32":
    "David says, \"Blessed is he whose transgressions are forgiven, whose sins are covered.\" When he kept his sin hidden, his body wasted away and God's hand was heavy on him. Then he confessed his sin to the LORD, and God forgave the guilt of his sin. Now God is his hiding place, and God promises, \"I will instruct you and teach you the way you should go.\"",
  "psalm-72":
    "Psalm 72 prays for a king who judges with God's justice and defends the poor. May he be like rain on cut grass, may his kingdom reach from sea to sea, and may kings from distant lands bring him gifts. All nations will honor him, \"for he will deliver the needy who cry out and the afflicted who have no helper,\" because their lives are precious to him. Christians see this king in Jesus, to whom the wise men brought gifts.",
  "psalm-96":
    "Psalm 96 calls all the earth to sing a new song to the LORD and tell the nations about his glory. The gods of the nations are idols, but the LORD made the heavens. All families of the nations are called to worship him and say, \"The LORD reigns!\" The heavens, the sea, the fields, and the trees of the forest sing for joy, because he is coming to judge the world in righteousness.",
  "psalm-103":
    "David tells his soul to bless the LORD and not forget all his kindness: he forgives all our sins, heals our diseases, and crowns us with love and compassion. The LORD is compassionate and gracious, slow to anger, and has not treated us as our sins deserve. As far as the east is from the west, so far has he removed our sins. Like a father, he has compassion on his children, for he knows we are dust.",
  "psalm-118":
    "Psalm 118 calls everyone to give thanks to the LORD, for his loving devotion endures forever. The singer was surrounded by enemies and pushed until he was falling, but the LORD helped him: \"I will not die, but I will live and proclaim what the LORD has done.\" He comes to the temple gates and sings, \"The stone the builders rejected has become the cornerstone. This is the day that the LORD has made.\" The crowds on Palm Sunday shouted words from this psalm.",
  "psalm-119":
    "Psalm 119 is the longest chapter in the Bible, a love song to God's word in 22 sections, one for each letter of the Hebrew alphabet. The writer says those who walk in God's law are blessed, and that a young person keeps their way pure by guarding it with God's word: \"I have hidden Your word in my heart.\" God's words are sweeter than honey, and \"Your word is a lamp to my feet and a light to my path.\"",
  "psalm-145":
    "David praises God his King every day: his greatness is beyond understanding, and one generation tells the next about his works. The LORD is gracious and compassionate, slow to anger, and good to all. His kingdom lasts forever. He lifts up all who fall, and \"the eyes of all look to You, and You give them their food in season.\" The LORD is near to all who call on him.",
  "psalm-147":
    "Psalm 147 praises the LORD, who builds up Jerusalem and gathers its exiles. \"He heals the brokenhearted and binds up their wounds. He determines the number of the stars; He calls them each by name.\" He sends rain, makes grass grow, and feeds the young ravens when they call. His word runs swiftly: he spreads snow like wool, and with another word melts it away.",
  "psalm-148":
    "Psalm 148 calls everything God made to praise him: angels in heaven, the sun, moon, and stars, sea creatures, lightning and hail, snow and wind, mountains and trees, wild animals and cattle, kings and all peoples, young men and maidens, old and young together. They should all praise the LORD, because he created them by his command and his name alone is exalted.",
  "be-holy":
    "God told Moses to tell all the people, \"Be holy because I, the LORD your God, am holy.\" Holiness meant leaving the edges of the harvest for the poor and the foreigner, not stealing or lying, paying workers on time, not cursing the deaf or tripping the blind, and judging fairly. It ended, \"Do not seek revenge or bear a grudge against any of your people, but love your neighbor as yourself. I am the LORD.\"",
  "do-not-forget":
    "Before God's people crossed into the promised land, Moses reminded them that no other nation had a god as near as the LORD whenever they called on him. He told them to fix God's words on their hearts and teach them to their children at home and on the road. He promised that God would raise up a prophet like him, and taught them to bring their first harvest to God and say, \"My father was a wandering Aramean,\" remembering how the LORD heard their cry and brought them out of Egypt.",
  "solomon-dedicates-the-temple":
    "When Solomon finished building the temple, the priests carried the ark of the covenant into the Most Holy Place, and a cloud filled the house, for the glory of the LORD filled it. Solomon spread out his hands and prayed, \"Even heaven, the highest heaven, cannot contain You, much less this temple I have built,\" and asked God to hear and forgive whenever his people prayed, even foreigners from distant lands. Then he blessed the people: \"Not one word has failed of all the good promises He made.\"",
  "hosea":
    "God told Hosea to marry Gomer, a woman who would be unfaithful, so that his marriage would show how God's people had been unfaithful to him. Yet God promised to speak tenderly to his people and win them back: \"I will betroth you to Me forever.\" He called them, \"Come, let us return to the LORD,\" and said, \"I desire mercy, not sacrifice.\" Like a parent who taught his child to walk, God cried out, \"How could I give you up?\"",
  "come-let-us-reason-together":
    "Isaiah told the busy worshipers of Jerusalem that God was tired of their sacrifices because their hands were covered with blood: \"Learn to do right; seek justice.\" Then God said, \"Come now, let us reason together. Though your sins are like scarlet, they will be as white as snow.\" Isaiah sang a sad song about a vineyard that grew sour grapes, and later promised a great feast on God's mountain for all peoples, where God \"will swallow up death forever\" and wipe away the tears from every face.",
  "fire-in-my-bones":
    "Jeremiah's own people plotted against him, and he told God how lonely and hurt he was: \"Why is my pain unending?\" God promised to make him a wall of bronze. Jeremiah said that the one who trusts in the LORD is like a tree planted by the water. Mocked all day long, he decided to stop speaking for God, but God's word was \"a fire burning in my heart, shut up in my bones.\" He warned against false prophets like Hananiah, who broke Jeremiah's wooden yoke and promised peace that would not come.",
  "great-is-your-faithfulness":
    "After Babylon destroyed Jerusalem, a poet wrote of his bitter sorrow. Then, right in the middle of his grief, he remembered: \"Because of the loving devotion of the LORD we are not consumed, for His mercies never fail. They are new every morning; great is Your faithfulness!\" He said, \"The LORD is my portion,\" and that it is good to wait quietly for God's salvation, because the Lord will not cast us off forever.",
  "turn-and-live":
    "God called Ezekiel among the exiles in Babylon and sent him to a stubborn people, \"whether they listen or refuse to listen.\" God promised to plant a tender sprig that would become a majestic cedar. When the people blamed their parents for their troubles, God said every soul belongs to him and called them to turn from their sins and \"fashion for yourselves a new heart.\" God made Ezekiel a watchman and told him to say, \"I take no pleasure in the death of the wicked, but rather that the wicked should turn from their ways and live.\"",
  "a-house-of-prayer-for-all-nations":
    "God said, \"I am the first and I am the last, and there is no God but Me.\" He called the Persian king Cyrus his anointed to set his people free. He told the people to look to Abraham, the rock they were cut from, and promised that his salvation would last forever. He welcomed foreigners and outsiders into his house, \"a house of prayer for all the nations,\" reached out to people who never sought him, and promised, \"As a mother comforts her son, so will I comfort you.\"",
  "your-king-comes-to-you":
    "The prophet Zechariah told the small, kingless city of Jerusalem, \"Rejoice greatly, O Daughter of Zion! See, your King comes to you, righteous and victorious, humble and riding on a donkey.\" This king would break the bow of war and proclaim peace to the nations. Because of the blood of God's covenant, he would set prisoners free, and God called his people \"prisoners of hope.\" On Palm Sunday, Jesus rode into Jerusalem on a donkey.",
  "the-sun-of-righteousness":
    "Through Malachi, God promised, \"I will send My messenger, who will prepare the way before Me,\" and then the Lord himself would come to his temple, like a refiner's fire, to make his people pure. For the proud, that day would burn like a furnace, but for those who fear God's name, \"the sun of righteousness will rise with healing in its wings.\" God promised to send Elijah to turn the hearts of parents and children toward each other. Jesus said John the Baptist was that messenger.",
  "1-thessalonians":
    "Paul wrote to the young church in Thessalonica after Timothy brought good news that they were standing firm. He thanked God for their work of faith, labor of love, and enduring hope, and reminded them how he had cared for them like a mother and a father. Some believers had died, so Paul told them not to grieve like people without hope: since Jesus died and rose, God will bring with him those who have fallen asleep, and \"we will always be with the Lord.\" He ended, \"Rejoice at all times. Pray without ceasing. Give thanks in every circumstance.\"",
  "god-makes-it-grow":
    "Paul reminded the Corinthians that he came to them in weakness and fear, resolved to know nothing among them except Jesus Christ and him crucified, so their faith would rest on God's power. God reveals by his Spirit what no eye has seen and no ear has heard. The church was quarreling over leaders, but Paul said, \"I planted the seed and Apollos watered it, but God made it grow.\" Jesus Christ is the only foundation, the church is God's temple, and leaders are servants who must be found faithful.",
  "ephesians-4-to-6":
    "Paul urged the church to keep the unity of the Spirit, because there is one body, one Spirit, one Lord, one faith, one baptism, and one God and Father of all. He told them to speak the truth in love, not let the sun set on their anger, and be kind and tenderhearted, forgiving each other just as God forgave them in Christ. They were to walk as children of light and be filled with the Spirit. Finally, he told them to be strong in the Lord and put on the full armor of God: truth, righteousness, the gospel of peace, faith, salvation, and the word of God.",
  "2-timothy":
    "From prison near the end of his life, Paul wrote to Timothy, his beloved child in the faith, remembering the sincere faith of his grandmother Lois and mother Eunice. He told him, \"God has not given us a spirit of fear, but of power, love, and self-control,\" and reminded him that even if we are faithless, Christ remains faithful. All Scripture is God-breathed, so Timothy should preach the word in season and out of season. Paul wrote, \"I have fought the good fight, I have finished the race, I have kept the faith,\" and said that though everyone deserted him, the Lord stood by him.",
  "jesus-our-great-high-priest":
    "Hebrews says that God, who spoke through the prophets, has now spoken by his Son, the exact representation of his nature. Jesus became like us in every way, was tempted as we are yet without sin, and freed us from the fear of death, so we can approach the throne of grace with confidence. As our great high priest, he offered himself once for all, entering the Most Holy Place by his own blood, and now always lives to pray for us. So let us draw near, hold on to our hope, keep meeting together, and remember that \"Jesus Christ is the same yesterday and today and forever.\"",
  "james":
    "James, the brother of Jesus, wrote to scattered Christians that trials can grow perseverance and that every good and perfect gift is from above. He told them to be quick to listen, slow to speak, and slow to anger, and to be \"doers of the word, and not hearers only.\" He warned against favoring the rich over the poor and said faith without deeds is dead. He warned that the tongue is like a small spark that sets a forest on fire, told them to draw near to God, and urged them to pray for each other, because the prayer of a righteous person has great power.",
  "worthy-is-the-lamb":
    "John saw a scroll sealed with seven seals, and wept because no one was worthy to open it. An elder told him that the Lion of the tribe of Judah had triumphed, and John saw a Lamb who had been slain, standing at the center of the throne. All creation sang, \"Worthy is the Lamb, who was slain,\" and John saw a multitude too large to count, from every nation, in robes washed white in the blood of the Lamb, who will be their shepherd. At the end, Jesus says, \"Yes, I am coming soon,\" and the church answers, \"Amen. Come, Lord Jesus!\"",
  "galatians":
    "Paul wrote to the churches in Galatia because teachers were telling them they had to keep the law of Moses to really belong to God. Paul said a person is justified by faith in Jesus, not by works of the law: \"I have been crucified with Christ, and I no longer live, but Christ lives in me.\" Everyone baptized into Christ is one in him, a child and heir of God, and people set free should serve one another in love as the Spirit grows his fruit: love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, and self-control.",
  "1-corinthians-12":
    "The church in Corinth was competing over spiritual gifts. Paul said there are different gifts but the same Spirit, given for the common good. The church is like a body with many parts: the foot can't say it doesn't belong because it isn't a hand, and the eye can't tell the hand, \"I do not need you.\" The parts that seem weaker are indispensable, and when one part suffers, every part suffers with it. \"Now you are the body of Christ, and each of you is a member of it.\"",
  "2-corinthians-5":
    "Paul says our bodies are like tents that wear out, but God has an eternal house ready for us, so we walk by faith, not by sight. Christ's love compels us, because he died for all so that we would live for him. \"If anyone is in Christ, he is a new creation.\" God reconciled the world to himself in Christ, not counting people's sins against them, and made us his ambassadors: \"Be reconciled to God.\" God made him who knew no sin to be sin for us, so that in him we might become the righteousness of God.",
  "not-ashamed-of-the-gospel":
    "Paul writes to the Christians in Rome, a church he had never visited, and names the theme of his whole letter: \"I am not ashamed of the gospel, because it is the power of God for salvation to everyone who believes.\" In the gospel, God reveals a righteousness that comes by faith, for \"the righteous will live by faith.\" Later he explains that all have sinned and fall short of the glory of God, and all are justified freely by his grace through Christ Jesus, by faith apart from works of the law.",
  "romans-6":
    "Paul asks, \"Shall we continue in sin so that grace may increase?\" and answers, \"Certainly not!\" Everyone baptized into Christ was baptized into his death, buried with him, so that just as Christ was raised from the dead, we too may walk in newness of life. Sin is no longer our master, because we are under grace. \"For the wages of sin is death, but the gift of God is eternal life in Christ Jesus our Lord.\"",
  "romans-12":
    "Because of God's mercy, Paul urges believers to offer their bodies as living sacrifices and not be conformed to this world but transformed by the renewing of their minds. In Christ, many people form one body with different gifts. Love must be sincere: be joyful in hope, patient in trouble, rejoice with those who rejoice and weep with those who weep. Don't repay evil for evil, feed your enemy if he is hungry, and \"overcome evil with good.\"",
  "colossians":
    "Paul wrote to Christians in Colossae, who were hearing that they needed more than Jesus. He told them that Jesus is the image of the invisible God: all things were created through him, and in him all things hold together. God forgave all our sins, cancelling the debt against us and nailing it to the cross. So set your minds on things above, where your life is hidden with Christ, and clothe yourselves with compassion and kindness: \"Forgive as the Lord forgave you,\" and over all these put on love.",
  "hebrews-11":
    "Hebrews 11 begins, \"Now faith is the assurance of what we hope for and the certainty of what we do not see.\" Then it lists people who lived by faith: Abel, Enoch, Noah, Abraham who went without knowing where he was going, Sarah, Moses, Rahab, and many more, some who shut lions' mouths and some who suffered and died. They all trusted God's promises before seeing them. Surrounded by this great cloud of witnesses, we run our race with our eyes fixed on Jesus, the author and perfecter of our faith.",
  "1-peter":
    "Peter wrote to Christians who were insulted and suffering for their faith. He told them God had given them new birth into a living hope through Jesus's resurrection, and that they were redeemed not with silver or gold but with the precious blood of Christ. They were living stones in God's house, \"a chosen people, a royal priesthood.\" Jesus suffered unjustly too, and by his wounds we are healed. \"Cast all your anxiety on Him, because He cares for you,\" and after a little while the God of all grace will restore you.",
  "1-john":
    "John, writing to the believers he calls his little children, says that God is light, and \"if we confess our sins, He is faithful and just to forgive us.\" He marvels at the love the Father has given us, that we should be called children of God. Love is not that we loved God, but that he loved us and sent his Son for our sins, so we love one another, and \"perfect love drives out fear.\" He wrote so that those who believe in Jesus may know that they have eternal life.",
  "a-new-heaven-and-a-new-earth":
    "John saw a new heaven and a new earth, and the holy city, the new Jerusalem, coming down from God. A loud voice said that God's dwelling is now with people: \"He will wipe away every tear from their eyes,\" and there will be no more death, mourning, crying, or pain. The One on the throne said, \"Behold, I make all things new.\" The city needs no temple and no sun, because God and the Lamb are its light, and a river of the water of life flows past the tree of life, whose leaves are for the healing of the nations.",
  "1-corinthians-1":
    "Paul writes to the church in Corinth, which was splitting into groups: \"I follow Paul,\" \"I follow Apollos,\" \"I follow Cephas.\" He asks, \"Is Christ divided? Was Paul crucified for you?\" Then he says the message of the cross is foolishness to the world but the power of God to those being saved, and that God chose the weak and lowly so that no one can boast except in the Lord.",
  "1-corinthians-15":
    "Paul reminds the Corinthians of the good news: Christ died for our sins, was buried, was raised on the third day, and appeared to Peter, the Twelve, more than five hundred people, and finally Paul. If Christ has not been raised, our faith is useless, but Christ has been raised as the firstfruits of all who have died. One day we will all be changed in the twinkling of an eye, death will be swallowed up in victory, and we will say, \"Where, O Death, is your sting?\"",
  "2-corinthians-4":
    "Paul tells the Corinthians that God, who said \"Let light shine out of darkness,\" has made his light shine in our hearts. \"We have this treasure in jars of clay,\" he says, so everyone can see the power is God's. He is hard pressed but not crushed, struck down but not destroyed, and though his outer self is wasting away, his inner self is being renewed day by day.",
  "romans-4":
    "Paul asks how Abraham was made right with God, and answers from Scripture: \"Abraham believed God, and it was credited to him as righteousness.\" It was a gift, not wages for work, and it happened before Abraham was circumcised, so he is the father of everyone who believes. Against all hope, Abraham trusted the God who gives life to the dead, and the same is credited to us who believe in the God who raised Jesus.",
  "romans-5":
    "Paul says that since we have been justified through faith, we have peace with God through Jesus. Suffering produces perseverance, character, and hope, and that hope does not disappoint because God has poured his love into our hearts. God proves his love in this: while we were still sinners, Christ died for us. Sin and death came through one man, Adam, but grace and life came through one man, Jesus, and where sin increased, grace increased all the more.",
  "romans-8":
    "Paul says there is now no condemnation for those who are in Christ Jesus. The Spirit makes us God's children, so we cry out, \"Abba! Father!\" All creation groans as it waits to be set free, the Spirit prays for us when we don't know what to pray, and God works all things together for the good of those who love him. Then Paul asks, \"If God is for us, who can be against us?\" and says nothing in all creation can separate us from the love of God in Christ Jesus.",
  "ephesians-1":
    "Paul praises God, who has blessed us in Christ with every spiritual blessing. God chose us in love to be his children, forgave our sins through Jesus's blood, and plans to bring all things together in Christ. Believers are sealed with the Holy Spirit as a promise of what is coming, and Paul prays that the eyes of their hearts will be opened to know God's hope and the power that raised Jesus from the dead.",
  "ephesians-2":
    "Paul says we were dead in our trespasses and sins. But because of his great love, God, who is rich in mercy, made us alive with Christ: \"It is by grace you have been saved through faith... it is the gift of God, not by works, so that no one can boast.\" Christ is our peace, who tore down the dividing wall between Jews and Gentiles, so that all believers are no longer strangers but members of God's household.",
  "ephesians-3":
    "From prison, Paul explains the mystery God has now revealed: through the gospel, Gentiles are fellow heirs with Israel and share fully in God's promise. Calling himself less than the least of all the saints, he prays that Christ will dwell in their hearts through faith and that they, rooted and grounded in love, will know the love of Christ that surpasses knowledge. He ends with praise to God, who is able to do immeasurably more than all we ask or imagine.",
  "the-grace-of-god-has-appeared":
    "Paul writes to Titus that the grace of God has appeared, bringing salvation to everyone and teaching us to live godly lives as we wait for the blessed hope, the appearing of our great God and Savior Jesus Christ. When God's kindness and love appeared, he saved us, not because of righteous deeds we had done, but by his mercy, through the washing of new birth and renewal by the Holy Spirit.",
  "as-for-me-and-my-house":
    "Near the end of his life, Joshua gathered all Israel at Shechem and told them everything God had done, from calling Abraham to giving them the land. Then he said, \"Choose for yourselves this day whom you will serve,\" and added, \"As for me and my house, we will serve the LORD!\" The people promised to serve the LORD, and Joshua set up a stone as a witness to their covenant.",
  "wisdom-calls-out":
    "In Proverbs, Wisdom is pictured as a woman who calls out to everyone at the crossroads and city gates. She says she was with God before the world began, beside him like a skilled craftsman, delighting in his creation and in people. Then she builds a house, sets a feast, and invites the simple: \"Come, eat my bread and drink the wine I have mixed.\"",
  "chasing-the-wind":
    "The Teacher of Ecclesiastes says, \"Futility of futilities! Everything is futile!\" Generations come and go, there is nothing new under the sun, and trying to grasp it all is like chasing the wind. He despaired that he would have to leave all his work to someone else, but then he saw that eating, drinking, and enjoying your work are gifts from the hand of God.",
  "let-justice-roll-down":
    "God sent Amos, a shepherd and fig farmer, to warn wealthy people in Israel who lived in luxury while cheating and trampling the poor. God said he hated their feasts and songs, because what he wanted was this: \"Let justice roll on like a river, and righteousness like an ever-flowing stream.\" God showed Amos a plumb line to measure his crooked people and promised never to forget how they cheated the needy.",
  "the-righteous-will-live-by-faith":
    "The prophet Habakkuk cried out, \"How long, O LORD, must I call for help but You do not hear?\" as violence and injustice filled the land. He stood on the watchtower to wait for God's answer, and God told him to write the vision down, because it would surely come, and said, \"The righteous will live by faith.\" Habakkuk ended singing that even if every crop failed, he would still rejoice in the God of his salvation.",
  "ezra-reads-the-law":
    "After the walls of Jerusalem were rebuilt, all the people gathered and asked Ezra to read the Book of the Law. He read from morning until noon while the Levites explained it so everyone could understand. The people wept as they heard it, but Nehemiah told them to celebrate and share food, saying, \"Do not grieve, for the joy of the LORD is your strength.\"",
  "jesus-goes-up-to-heaven":
    "For forty days after he rose, Jesus appeared to his apostles and told them to wait in Jerusalem for the Holy Spirit. He said, \"You will receive power when the Holy Spirit comes upon you, and you will be My witnesses... to the ends of the earth,\" and then he was taken up and a cloud hid him. Two men in white said he would come back the same way, and the believers went back to Jerusalem to pray and chose Matthias to take Judas's place.",
  "peter-and-john-heal-a-lame-man":
    "At the temple gate, a man who had never walked asked Peter and John for money, and Peter said, \"Silver or gold I do not have, but what I have I give you: In the name of Jesus Christ of Nazareth, get up and walk!\" The man jumped up, walking and leaping and praising God. Arrested and questioned, Peter told the council there is no other name by which we must be saved, and the apostles said, \"We cannot stop speaking about what we have seen and heard.\"",
  "we-must-obey-god":
    "The jealous high priest arrested the apostles, but during the night an angel opened the jail and told them to go preach in the temple. Brought before the council and ordered to stop, Peter said, \"We must obey God rather than men,\" and told them God raised Jesus as Prince and Savior. A teacher named Gamaliel warned the council that if this was from God they could not stop it, and the apostles left rejoicing to suffer for Jesus's name.",
  "stephen":
    "Stephen was one of seven men chosen to care for widows in the church, full of faith and the Holy Spirit. Falsely accused, he stood before the council with a face like an angel's and saw heaven open and Jesus standing at God's right hand. As they stoned him, with a young man named Saul watching, Stephen prayed, \"Lord Jesus, receive my spirit,\" and \"Lord, do not hold this sin against them.\"",
  "philip-and-the-ethiopian":
    "An angel sent Philip to a desert road, where an Ethiopian official was riding home reading Isaiah. Philip asked, \"Do you understand what you are reading?\" and the man said, \"How can I, unless someone guides me?\" Starting with Isaiah's words about a lamb led to the slaughter, Philip told him about Jesus, and when they came to water, the man was baptized and went on his way rejoicing.",
  "peter-raises-tabitha":
    "In Lydda, Peter said to a man paralyzed for eight years, \"Jesus Christ heals you!\" and he got up. In nearby Joppa, a disciple named Tabitha, who was always doing kind things and sewing clothes for widows, got sick and died. The believers sent for Peter, who knelt and prayed and said, \"Tabitha, get up!\" She opened her eyes and sat up, and many people believed in the Lord.",
  "abraham-and-sarah-get-new-names":
    "When Abram was ninety-nine, God appeared to him and said, \"I am God Almighty,\" and made an everlasting covenant with him. God changed his name to Abraham, \"father of many,\" and his wife Sarai's name to Sarah, and promised them a son. Abraham fell on his face and laughed, because he was a hundred and Sarah was ninety, but God said their son would be named Isaac.",
  "moses-on-the-mountain":
    "God called Moses up Mount Sinai to receive the stone tablets, and the glory of the LORD covered the mountain like a consuming fire. Moses went into the cloud and stayed forty days and forty nights. Later, when he came down with the tablets, his face was shining from speaking with God, so he wore a veil over it.",
  "hear-o-israel":
    "Before God's people entered the promised land, Moses taught them the words at the center of their faith: \"Hear, O Israel: The LORD our God, the LORD is One.\" Love the LORD your God with all your heart, soul, and strength. Keep these words on your heart, and talk about them with your children at home and on the road, when you lie down and when you get up.",
  "choose-life":
    "In his farewell message, Moses told God's people that God's word was not far away in heaven or across the sea, but very near, in their mouths and hearts. He set before them life and death, blessing and cursing, and urged them, \"Therefore choose life,\" by loving the LORD, obeying him, and holding fast to him, \"for He is your life.\"",
  "gods-promise-to-david":
    "King David, living in a palace of cedar, wanted to build a house for God, because the ark of God was still in a tent. But God told the prophet Nathan that he had never asked for a house, and that he had taken David from following the sheep to be king. Instead, God promised to build David a house, a family of kings, saying, \"Your throne will be established forever.\"",
  "job":
    "Job was a good man who loved God, and in one terrible day he lost his flocks, his servants, and all ten of his children, yet he said, \"The LORD gave, and the LORD has taken away. Blessed be the name of the LORD.\" Covered with sores and blamed by his friends, he cried out to God and held on: \"I know that my Redeemer lives.\" At last God answered him out of the whirlwind, Job said, \"Now my eyes have seen You,\" and God restored him.",
  "swords-into-plowshares":
    "Isaiah saw a day when the mountain of the LORD's house would be the highest of all, and people of every nation would stream to it, saying, \"Come, let us go up to the mountain of the LORD,\" to learn his ways. God would settle disputes between nations, and they would beat their swords into plowshares and never train for war again. So Isaiah invited God's people: \"Let us walk in the light of the LORD.\"",
  "immanuel":
    "When two kings attacked Jerusalem, King Ahaz and his people trembled like trees in the wind. Isaiah told him, \"Do not be afraid,\" and offered him any sign from God, but Ahaz refused to ask. So Isaiah said God would give a sign anyway: \"Behold, the virgin will be with child and will give birth to a son, and will call Him Immanuel,\" which means God with us.",
  "out-of-bethlehem":
    "The prophet Micah promised that out of Bethlehem, a town too small to notice, would come a ruler for Israel whose origins are from eternity. After a time of waiting, until a mother gave birth, he would shepherd his flock in the strength of the LORD. His greatness would reach the ends of the earth, and \"He will be our peace.\"",
  "do-justice-love-mercy":
    "Through the prophet Micah, God brought his people to court with the mountains as witnesses, asking, \"My people, what have I done to you?\" and reminding them how he rescued them from Egypt. The people asked whether God wanted thousands of rams or rivers of oil. Micah answered: \"What does the LORD require of you but to act justly, to love mercy, and to walk humbly with your God?\"",
  "god-sings-over-you":
    "After warning about the day of the LORD, the prophet Zephaniah ends with a song: \"Sing for joy, O Daughter of Zion,\" because the LORD has taken away your punishment. \"The LORD your God is among you; He is mighty to save. He will rejoice over you with gladness; He will quiet you with His love; He will rejoice over you with singing.\" God promises to save the lame and gather the scattered.",
  "god-calls-jeremiah":
    "God told the young Jeremiah, \"Before I formed you in the womb I knew you,\" and appointed him a prophet to the nations. Jeremiah protested that he was only a child and didn't know how to speak. God said, \"Do not be afraid of them, for I am with you,\" touched his mouth, and said, \"I have put My words in your mouth.\"",
  "i-will-shepherd-my-sheep":
    "Because Israel's leaders, its shepherds, had scattered God's people, God said, \"I Myself will search for My flock.\" He promised to gather them, feed them in good pasture, seek the lost, bind up the broken, and strengthen the weak. He would stop the strong sheep from bullying the weak and set over them one shepherd, his servant David.",
  "the-son-of-man-vision":
    "In a vision, Daniel saw the Ancient of Days take his seat on a throne of fire, and the beasts that stood for cruel empires lose their power. Then he saw one like a Son of Man coming with the clouds of heaven, who was given an everlasting kingdom that will never be destroyed. Later, an angel told Daniel that God's people would be delivered and that many who sleep in the dust would awake to everlasting life.",
  "a-light-to-the-nations":
    "God introduced his chosen servant, full of his Spirit, who would not break a bruised reed and would be a light to the nations, opening blind eyes. The servant felt he had labored in vain, but God sent him to bring salvation to the ends of the earth. When God's people said, \"The Lord has forgotten me,\" God answered that even if a mother could forget her child, he would not forget them: \"I have inscribed you on the palms of My hands.\"",
  "the-fast-god-chooses":
    "God's people complained that they fasted and God didn't notice, but on their fast days they mistreated workers and fought. God said the fast he chooses is to break the chains of wickedness, set the oppressed free, share bread with the hungry, and shelter the poor. Then, he promised, \"your light will break forth like the dawn,\" and when they called, he would say, \"Here I am.\"",
  "tear-open-the-heavens":
    "God's people remembered how the LORD carried them in the past, then prayed, \"If only You would rend the heavens and come down!\" They confessed that even their righteous acts were like filthy rags and their sins had blown them away like leaves. But they held on: \"O LORD, You are our Father; we are the clay, and You are the potter.\"",
  "isaiah-sees-the-lord":
    "In the year King Uzziah died, Isaiah saw the Lord on a throne in the temple, with seraphim calling, \"Holy, holy, holy is the LORD of Hosts.\" Isaiah cried, \"Woe is me,\" because he was a man of unclean lips, but a seraph touched his mouth with a burning coal and said his sin was taken away. When God asked, \"Whom shall I send?\" Isaiah answered, \"Here am I. Send me!\"",
  "a-child-is-born":
    "In a dark time, when enemies had conquered the north of Israel, Isaiah promised that people walking in darkness would see a great light. God would break the yoke of their oppressors, not with an army, but with a child: \"For unto us a child is born, unto us a son is given.\" He would be called Wonderful Counselor, Mighty God, Everlasting Father, Prince of Peace, and his kingdom of peace would never end.",
  "the-shoot-of-jesse":
    "Isaiah promised that from the stump of Jesse, the family of King David that looked cut down and dead, a new shoot would grow. The Spirit of the LORD would rest on this King, and he would judge the poor with fairness. In his kingdom the wolf would live with the lamb, a little child would lead them, and the earth would be full of the knowledge of the LORD.",
  "the-desert-will-bloom":
    "Isaiah promised that the desert would rejoice and blossom, and told God's people to strengthen weak hands and say to anxious hearts, \"Be strong, do not fear! Behold, your God will come.\" When God comes, the blind will see, the deaf will hear, the lame will leap, and water will gush in the wilderness. The redeemed will walk home on a highway called the Way of Holiness, singing, and sorrow and sighing will flee.",
  "a-new-covenant":
    "In the middle of disaster, the prophet Jeremiah brought God's message: \"I have loved you with an everlasting love.\" God promised to bring his scattered people home, the blind and lame among them, and to turn their mourning into joy. Then he promised a new covenant, not written on stone but on their hearts, in which \"I will forgive their iniquities and will remember their sins no more.\"",
  "the-righteous-branch":
    "Through the prophet Jeremiah, God warned the leaders of his people, called shepherds, who had scattered his flock. God promised to gather the sheep himself and give them good shepherds. He promised to raise up for David a righteous Branch, a King who would rule with justice, called \"The LORD Our Righteousness.\"",
  "i-have-called-you-by-name":
    "To his people in exile, who felt forgotten, God said, \"Do not fear, for I have redeemed you; I have called you by your name; you are Mine!\" He promised to be with them when they passed through deep waters and fire, because they were precious to him. He promised to do something new, making a way in the wilderness, and to blot out their sins and remember them no more.",
  "the-suffering-servant":
    "In Isaiah, God's servant speaks of setting his face like flint and not hiding from those who beat and mocked him. Then God says his servant will be lifted up, and the people confess that he was despised and rejected, and that he was pierced for their transgressions, and by his stripes they are healed. Like a lamb led to the slaughter, he poured out his life for others, and after his suffering, he would see the light of life.",
  "come-to-the-waters":
    "God calls out like a seller in a market: \"Come, all you who are thirsty, come to the waters,\" and buy without money. He invites people to stop spending on what doesn't satisfy, to seek him while he is near, and to return to him, because he will freely pardon. His ways are higher than ours, his word will not return empty, and creation will sing as his people go out in joy.",
  "arise-shine":
    "To discouraged people in a ruined Jerusalem, God said, \"Arise, shine, for your light has come.\" Darkness covers the earth, but the glory of the LORD rises over his people like the sun. Nations and kings will come to that light, bringing gold and frankincense and singing God's praises.",
  "good-news-to-the-poor":
    "Someone filled with God's Spirit says, \"The LORD has anointed Me to preach good news to the poor,\" to bind up the brokenhearted, free the captives, and comfort all who mourn, giving them a crown of beauty for ashes. God promises to rebuild ruined cities because he loves justice, and his people sing that he has clothed them with garments of salvation. Centuries later, Jesus read these words in Nazareth and said they were fulfilled.",
  "peter-and-cornelius":
    "An angel told Cornelius, a Roman centurion who prayed to God, to send for Peter. Meanwhile, Peter saw a vision of a sheet full of unclean animals and heard, \"Do not call anything impure that God has made clean.\" Peter went to Cornelius's house, said, \"God does not show favoritism,\" and told them about Jesus, and while he was speaking, the Holy Spirit came on everyone listening, and they were baptized.",
  "abrahams-visitors":
    "Three visitors came to Abraham's tent in the heat of the day, and he ran to welcome them with a feast. One of them was the LORD, who promised that Sarah, though very old, would have a son, and when Sarah laughed, he asked, \"Is anything too difficult for the LORD?\" Then the LORD told Abraham about the outcry against Sodom, and Abraham pleaded for the city until God agreed to spare it for the sake of ten righteous people.",
  "jacob-wrestles-with-god":
    "On the night before he was to meet his brother Esau, whom he had cheated years before, Jacob was alone by the Jabbok River, and a man wrestled with him until daybreak. When the man touched Jacob's hip and asked to be let go, Jacob said, \"I will not let you go unless you bless me.\" The man gave him a new name, Israel, and blessed him, and Jacob limped away saying he had seen God face to face.",
  "manna-from-heaven":
    "In the desert, the hungry Israelites grumbled that they would have been better off as slaves in Egypt. God sent quail in the evening and, every morning, flakes of bread called manna, enough for each person for one day and a double portion before the Sabbath, and he fed them this way for forty years. Later, when there was no water, God told Moses to strike a rock, and water poured out for the people to drink.",
  "the-golden-calf":
    "While Moses was on Mount Sinai receiving God's commandments, the people grew tired of waiting and Aaron made them a golden calf to worship. God told Moses he would destroy them, but Moses pleaded for the people, and the LORD relented. Moses came down, broke the stone tablets, and destroyed the calf, then went back to God and prayed, \"If You would only forgive their sin,\" even offering himself in their place.",
  "the-bronze-snake":
    "Near the end of their years in the desert, the Israelites grew impatient and spoke against God and Moses, even saying they hated the manna. Poisonous snakes came into the camp, and when the people confessed their sin, Moses prayed for them. God told Moses to make a bronze snake and lift it up on a pole, and anyone who was bitten and looked at it lived.",
  "hannahs-prayer":
    "Hannah had no children, and her husband's other wife taunted her year after year until she wept. At God's house in Shiloh she poured out her soul to the LORD and promised that if he gave her a son, she would give him back to serve God. God answered, and she named her son Samuel, brought him to serve at Shiloh, and sang, \"There is no one holy like the LORD.\"",
  "david-is-anointed":
    "God sent Samuel to Bethlehem to anoint one of Jesse's sons as the next king. When Samuel saw the tall oldest son, God said, \"Man sees the outward appearance, but the LORD sees the heart,\" and seven sons were passed over. The youngest, David, was out with the sheep, and when he came in, God said, \"He is the one,\" and Samuel anointed him.",
  "david-and-bathsheba":
    "King David stayed home from the war, saw Bathsheba bathing, took her to the palace and slept with her, and when she became pregnant, he arranged for her husband Uriah to be killed in battle. God sent the prophet Nathan, who told a story about a rich man who stole a poor man's only lamb, and when David was outraged, Nathan said, \"You are that man!\" David confessed, \"I have sinned against the LORD,\" and Nathan said, \"The LORD has taken away your sin.\"",
  "the-wisdom-of-solomon":
    "God appeared to young King Solomon in a dream and said, \"Ask, and I will give it to you!\" Solomon asked for an understanding heart to judge God's people, and God gave him wisdom, along with riches and honor he hadn't asked for. Soon two women came to him, each claiming the same baby, and when Solomon called for a sword, the real mother begged him to give the baby to the other woman, so Solomon knew she was the mother.",
  "elijah-and-the-widow":
    "Elijah announced a drought, and God fed him by a stream with bread and meat brought by ravens. Then God sent him to a poor widow in Zarephath who had only a handful of flour and a little oil left, and when she shared it with Elijah, her flour and oil did not run out until the rain came. Later, when her son died, Elijah cried out to the LORD, and God brought the boy back to life.",
  "elijah-goes-up-to-heaven":
    "On the day God was going to take Elijah away, his student Elisha refused three times to leave him. Elijah parted the Jordan River with his cloak, and Elisha asked for a double portion of his spirit. Then a chariot of fire with horses of fire came between them, and Elijah went up into heaven in a whirlwind; Elisha picked up his cloak, struck the river, and it parted for him too.",
  "naaman-is-healed":
    "Naaman, a powerful army commander from Aram, had leprosy, and a captive Israelite girl told his wife about a prophet in Israel who could heal him. The prophet Elisha sent word for him to wash seven times in the Jordan River, and Naaman went away angry, but his servants persuaded him to try. He dipped himself seven times, his skin became like a little child's, and he declared that there is no God in all the earth except in Israel.",
  "the-valley-of-dry-bones":
    "In a vision, God set the prophet Ezekiel in a valley full of very dry bones and asked, \"Son of man, can these bones come to life?\" When Ezekiel spoke God's word, the bones came together and were covered with flesh, and when he called the breath, they came to life and stood up like a vast army. God explained that the bones were his hopeless people in exile, and promised, \"I will put My Spirit in you and you will live.\"",
  "lord-of-the-sabbath":
    "One Sabbath, Jesus's hungry disciples picked grain as they walked, and the Pharisees said it was against the law. Jesus reminded them that David once ate the holy bread when he was hungry, and said, \"The Sabbath was made for man, not man for the Sabbath.\" Later, in a synagogue, Jesus asked whether it is right to do good on the Sabbath and healed a man's withered hand, and the leaders began to plot against him.",
  "jesus-true-family":
    "So many people crowded around Jesus that he couldn't eat, and his family came to take him home, saying he was out of his mind. Scribes from Jerusalem said he drove out demons by the devil's power, but Jesus answered that a house divided against itself cannot stand, and that he had come to tie up the strong man. When his mother and brothers sent for him, he looked at the people around him and said, \"Here are My mother and My brothers! For whoever does the will of God is My brother and sister and mother.\"",
  "you-have-heard-it-said":
    "In the Sermon on the Mount, Jesus took God's commandments one at a time and showed how deep they go. He said anger and insults break the command against murder, and that people should make peace with each other even before bringing an offering to God. He said faithfulness starts in the heart, that God means marriage to last, and that his followers should simply let their \"yes\" be \"yes\" and their \"no\" be \"no.\"",
  "the-widow-of-nain":
    "At the gate of the town of Nain, Jesus met a funeral: a widow's only son was being carried out to be buried. Jesus had compassion on her and said, \"Do not weep.\" He touched the coffin and said, \"Young man, I tell you, get up!\" The dead man sat up and began to speak, Jesus gave him back to his mother, and the crowd praised God, saying, \"God has visited His people!\"",
  "the-man-among-the-tombs":
    "Across the lake from Galilee, a man controlled by many demons lived among the tombs, and no chains could hold him. When Jesus asked his name, he said \"Legion,\" and Jesus sent the demons out of him and into a herd of pigs, which rushed into the lake. The townspeople found the man sitting at Jesus's feet, dressed and in his right mind, and were afraid, so Jesus left, but first he sent the man home to tell how much God had done for him.",
  "are-you-the-one":
    "From prison, John the Baptist sent his disciples to ask Jesus, \"Are You the One who was to come?\" Jesus told them to report what they saw: the blind see, the lame walk, the dead are raised, and the poor hear good news. Then Jesus praised John to the crowds, thanked his Father for revealing these things to little children, and said, \"Come to Me, all you who are weary and burdened, and I will give you rest.\"",
  "the-death-of-john-the-baptist":
    "King Herod had put John the Baptist in prison because John told him it was wrong to marry his brother's wife. Herodias held a grudge against John, and at Herod's birthday party, after her daughter danced, Herod promised the girl anything she asked. At her mother's urging she asked for John's death, and Herod, unwilling to break his promise in front of his guests, had John killed; his disciples came and buried him.",
  "what-comes-from-the-heart":
    "Some Pharisees and scribes complained that Jesus's disciples ate without washing their hands the way tradition required. Jesus quoted Isaiah, \"These people honor Me with their lips, but their hearts are far from Me,\" and said they set aside God's commands to keep their own traditions. He told the crowd that nothing going into a person from outside makes them unclean, because evil thoughts and actions come from within the heart.",
  "whoever-is-not-against-us":
    "John told Jesus they had tried to stop a man who was driving out demons in Jesus's name because he wasn't one of them, but Jesus said, \"Do not stop him. Whoever is not against us is for us.\" He said even a cup of water given in his name will be rewarded, and warned strongly against causing one of his little ones to stumble. Using shocking pictures, he told them to take sin seriously, and said, \"Be at peace with one another.\"",
  "when-someone-wrongs-you":
    "Jesus told his disciples that if a fellow believer sins against them, they should go and talk to that person privately, hoping to win them back. If that doesn't work, they should bring one or two others along, and then tell the church. He said that what they bind or loose on earth will be bound or loosed in heaven, and promised, \"Where two or three gather together in My name, there am I with them.\"",
  "jesus-sets-out-for-jerusalem":
    "Jesus set out for Jerusalem with his mind made up. When a Samaritan village wouldn't welcome him, James and John wanted to call down fire from heaven, but Jesus rebuked them. On the road, he told someone who offered to follow that he had no place to lay his head, and told others who wanted to follow later that no one who puts a hand to the plow and looks back is fit for the kingdom of God.",
  "fire-on-the-earth":
    "On the way to Jerusalem, Jesus said he came to bring fire on the earth, and that he had a baptism of suffering to go through. He warned that people would be divided over him, even in families. He told the crowds they could read the weather from the sky but could not see what God was doing in front of them, and urged them to make peace while there was still time.",
  "jesus-heals-a-bent-over-woman":
    "One Sabbath, Jesus saw a woman in the synagogue who had been bent over for eighteen years and could not stand up straight. He called her over, said, \"Woman, you are set free from your disability,\" and put his hands on her, and she stood up straight and praised God. When the synagogue leader complained about healing on the Sabbath, Jesus said that if they untie their animals on the Sabbath, this daughter of Abraham should surely be set free, and the crowd rejoiced.",
  "the-lowest-seat":
    "At a Sabbath dinner at a leading Pharisee's house, Jesus healed a man and then noticed the guests choosing the best seats. He told them to take the lowest seat instead, so the host could say, \"Friend, move up to a better place,\" because everyone who exalts himself will be humbled, and the humble will be exalted. He told the host to invite the poor, the crippled, the lame, and the blind, who can't pay him back.",
  "mary-anoints-jesus":
    "Six days before Passover, at a dinner in Bethany with Martha and Lazarus, Mary poured a pint of very expensive perfume on Jesus's feet and wiped them with her hair, and the house was filled with the fragrance. Judas Iscariot complained that the perfume should have been sold and the money given to the poor, though he was really a thief. Jesus said, \"Leave her alone,\" and that she had kept it for the day of his burial.",
  "the-grain-of-wheat":
    "In Jerusalem before Passover, some Greeks asked Philip, \"Sir, we want to see Jesus.\" Jesus said the hour had come, and that unless a kernel of wheat falls into the ground and dies, it remains a single seed, but if it dies, it bears much fruit. Though his soul was troubled, he prayed, \"Father, glorify Your name!\" A voice answered from heaven, and Jesus said that when he is lifted up from the earth, he will draw everyone to himself.",
  "give-to-caesar":
    "In the temple courts, spies tried to trap Jesus by asking whether it was right to pay taxes to Caesar. Jesus asked whose image was on a coin and said, \"Give to Caesar what is Caesar's, and to God what is God's.\" Then some Sadducees, who did not believe in the resurrection, asked whose wife a woman married to seven brothers would be, and Jesus said that God is not the God of the dead, but of the living.",
  "the-widows-offering":
    "In the temple, Jesus warned about scribes who showed off and took advantage of widows. Then he sat watching people put money in the offering boxes, where rich people gave large amounts and a poor widow put in two small copper coins. Jesus told his disciples that she had given more than all the others, because they gave out of their extra, but she gave all she had to live on.",
  "practice-what-you-preach":
    "In the temple courts, Jesus told the crowds to follow what the scribes and Pharisees taught from God's law, but not to copy what they did, because they didn't practice what they preached. He said they put heavy loads on people without helping, and did their good deeds to be seen. He told his followers they have one Teacher and one Father, and that the greatest among them shall be their servant.",
  "the-boy-jesus-at-the-temple":
    "When Jesus was twelve, his family went to Jerusalem for Passover, and on the way home Mary and Joseph realized he was missing. After three days they found him in the temple courts, listening to the teachers and asking questions. Jesus said, \"Did you not know that I had to be in My Father's house?\" Then he went home to Nazareth, obeyed his parents, and grew in wisdom and stature.",
  "jesus-is-rejected-at-nazareth":
    "In the synagogue in Nazareth, his hometown, Jesus read from Isaiah: the Spirit of the Lord is on him to bring good news to the poor, freedom for captives, and sight for the blind. He said, \"Today this Scripture is fulfilled in your hearing.\" When he reminded them that God's kindness had gone to outsiders in the days of Elijah and Elisha, the crowd tried to throw him off a cliff, but Jesus walked through them and went on his way.",
  "the-faith-of-the-centurion":
    "In Capernaum, a Roman centurion's servant was dying, and Jewish elders asked Jesus to come, saying the centurion deserved it. As Jesus came near, the centurion sent friends to say, \"I am not worthy to have You come under my roof. But just say the word, and my servant will be healed.\" Jesus was amazed and said he had not found such great faith even in Israel, and the servant was healed.",
  "jesus-sends-out-the-twelve":
    "Jesus saw the crowds were like sheep without a shepherd and told his disciples to pray for workers for the harvest. Then he gave his twelve apostles authority to heal and sent them out to preach that the kingdom of heaven is near, warning them they would be like sheep among wolves. He told them not to be afraid, because God watches over every sparrow and knows every hair on their heads.",
  "the-faith-of-the-canaanite-woman":
    "Near Tyre and Sidon, a Canaanite woman begged Jesus to have mercy on her daughter, who was suffering from a demon. At first Jesus did not answer, and when he said it was not right to give the children's bread to the dogs, she answered, \"Even the dogs eat the crumbs that fall from their master's table.\" Jesus said, \"O woman, your faith is great!\" and her daughter was healed that very hour.",
  "who-is-the-greatest":
    "After Jesus told his disciples again that he would be killed and rise, they argued on the road about who was the greatest. Jesus said whoever wants to be first must be the servant of all, and he took a little child in his arms. Later James and John asked for the best seats in his glory, and Jesus said, \"Even the Son of Man did not come to be served, but to serve, and to give His life as a ransom for many.\"",
  "the-greatest-commandment":
    "In the temple courts, a scribe asked Jesus which commandment is the most important. Jesus said, \"Love the Lord your God with all your heart and with all your soul and with all your mind and with all your strength,\" and second, \"Love your neighbor as yourself.\" The scribe agreed, and Jesus told him, \"You are not far from the kingdom of God.\"",
  "jesus-speaks-about-the-end":
    "As Jesus left the temple, he said not one of its stones would be left standing. On the Mount of Olives, he told four disciples not to be fooled or alarmed by wars, earthquakes, and false christs, and warned that his followers would be treated badly. He said the Son of Man will come in the clouds with great power, that no one knows the day or hour, and that his words will never pass away, so keep watch.",
  "jesus-washes-the-disciples-feet":
    "On the night before he died, Jesus got up from supper, wrapped a towel around his waist, and washed his disciples' feet. Peter said, \"Never!\" but Jesus said, \"Unless I wash you, you have no part with Me,\" and told them to serve one another the same way. After Judas went out into the night to betray him, Jesus gave them a new commandment: \"Love one another. As I have loved you, so you also must love one another.\"",
  "i-am-the-way":
    "On the night before he died, Jesus told his frightened disciples not to let their hearts be troubled, because he was going to prepare a place for them in his Father's house. When Thomas asked the way, Jesus said, \"I am the way and the truth and the life,\" and when Philip asked to see the Father, Jesus said anyone who has seen him has seen the Father. He promised to send the Holy Spirit and left them his peace.",
  "the-vine-and-the-branches":
    "Jesus told his disciples that he is the true vine, his Father is the gardener, and they are the branches. A branch can only bear fruit by staying on the vine, so he told them, \"Remain in Me,\" and \"Remain in My love.\" He commanded them to love one another as he loved them, called them his friends, and said, \"You did not choose Me, but I chose you.\"",
  "the-spirit-of-truth":
    "Jesus warned his disciples that the world would hate them as it hated him, but promised to send the Advocate, the Spirit of truth, who would testify about him. He told them it was for their good that he was going away, because then the Spirit would come. The Spirit would guide them into all truth and glorify Jesus by making him known.",
  "jesus-prays-for-his-followers":
    "Before he went to the garden where he was arrested, Jesus looked up to heaven and prayed. He prayed that the Father would glorify him, that the Father would protect his disciples from the evil one and make them holy by the truth of God's word, and that everyone who would believe through their message would be one. He ended by asking that they would be with him and see his glory.",
  "jesus-appears-to-the-disciples":
    "On Easter evening, Jesus suddenly stood among his disciples and said, \"Peace be with you,\" but they thought he was a ghost. He showed them his hands and feet and ate a piece of fish in front of them, then opened their minds to understand the Scriptures and sent them to preach forgiveness to all nations. Later, near Bethany, he lifted his hands and blessed them as he was carried up into heaven, and they returned to Jerusalem with great joy.",
  "jesus-is-tempted":
    "After his baptism, the Spirit led Jesus into the wilderness, where he fasted for forty days and was hungry. The devil tempted him three times: to turn stones into bread, to throw himself down from the temple, and to worship the devil in exchange for all the kingdoms of the world. Each time Jesus answered with God's word, the devil left him, and angels came and cared for him.",
  "jesus-heals-in-capernaum":
    "On the Sabbath in Capernaum, Jesus taught in the synagogue with authority, and when a man with an unclean spirit cried out, Jesus commanded it to come out, and it obeyed. Then Jesus healed Simon's mother-in-law of a fever, and that evening the whole town brought their sick to the door. Early the next morning, Jesus went off alone to pray, then moved on to preach in other towns.",
  "jesus-heals-a-man-with-leprosy":
    "A man with leprosy, who had to live apart from everyone, knelt before Jesus and said, \"If You are willing, You can make me clean.\" Jesus, moved with compassion, touched him and said, \"I am willing. Be clean!\" and the man was healed at once. Jesus told him to show himself to the priest, but the man told everyone, so Jesus had to stay out in lonely places.",
  "jesus-clears-the-temple":
    "At Passover, Jesus found people selling animals and changing money in the temple courts, so he made a whip of cords, drove them out, and overturned the tables, saying, \"How dare you turn My Father's house into a marketplace!\" When the leaders demanded a sign, Jesus said, \"Destroy this temple, and in three days I will raise it up again.\" He meant his body, and after he rose from the dead, his disciples remembered and believed.",
  "jesus-heals-a-man-born-blind":
    "Jesus's disciples asked whose sin made a man blind from birth, and Jesus said it was no one's. He put mud on the man's eyes and sent him to wash in the Pool of Siloam, and the man came back seeing. The Pharisees questioned him and his frightened parents, and when the man said, \"I was blind, but now I see!\" and defended Jesus, they threw him out. Jesus found him, and the man said, \"Lord, I believe,\" and worshiped him.",
  "the-bread-of-life":
    "The day after Jesus fed the 5,000, the crowd found him in Capernaum, wanting more bread. Jesus told them not to work for food that perishes and said, \"I am the bread of life,\" the true bread from heaven, who gives his flesh for the life of the world. Many followers found this too hard and left, but when Jesus asked the Twelve if they would leave too, Peter said, \"Lord, to whom would we go? You have the words of eternal life.\"",
  "mary-and-martha":
    "Martha welcomed Jesus into her home and was busy with all the preparations, while her sister Mary sat at Jesus's feet listening. Martha asked Jesus to tell Mary to help her. Jesus answered, \"Martha, Martha, you are worried and upset about many things. But only one thing is necessary,\" and said Mary had chosen the good portion.",
  "jesus-heals-ten-lepers":
    "On his way to Jerusalem, Jesus was met by ten men with leprosy, who called from a distance, \"Jesus, Master, have mercy on us!\" He told them to show themselves to the priests, and on the way they were healed. Only one came back to praise God and thank Jesus, and he was a Samaritan. Jesus asked where the other nine were, and told him, \"Rise and go; your faith has made you well!\"",
  "jesus-blesses-the-children":
    "People brought little children to Jesus so he would bless them, but the disciples scolded them. Jesus was indignant and said, \"Let the little children come to Me, and do not hinder them! For the kingdom of God belongs to such as these.\" He said anyone who does not receive God's kingdom like a little child will never enter it, and he took the children in his arms and blessed them.",
  "the-rich-young-man":
    "A man ran up, knelt before Jesus, and asked what he must do to inherit eternal life, saying he had kept the commandments since he was young. Jesus looked at him, loved him, and told him to sell everything, give to the poor, and follow him, but the man went away sad, because he had great wealth. Jesus said it is easier for a camel to go through the eye of a needle than for a rich man to enter God's kingdom, and when the disciples asked who could be saved, he said, \"All things are possible with God.\"",
  "blind-bartimaeus":
    "As Jesus left Jericho, a blind beggar named Bartimaeus shouted, \"Jesus, Son of David, have mercy on me!\" and shouted louder when the crowd told him to be quiet. Jesus stopped and called him, and Bartimaeus threw off his cloak and came. Jesus asked, \"What do you want Me to do for you?\" and when Bartimaeus asked to see, he was healed at once and followed Jesus along the road.",
  "the-great-commission":
    "After he rose from the dead, Jesus met the eleven disciples on a mountain in Galilee, where they worshiped him, though some doubted. Jesus said all authority in heaven and on earth had been given to him and sent them to make disciples of all nations, baptizing them in the name of the Father, the Son, and the Holy Spirit, and teaching them. His last words were a promise: \"And surely I am with you always, even to the end of the age.\"",
  "the-word-became-flesh":
    "John begins his Gospel before anything was made: the Word was with God and was God, and everything was made through him. John the Baptist came to point people to this Light, and to all who receive him, the Word gives the right to become children of God. Then the Word became flesh and lived among us, full of grace and truth, and he has made God known.",
  "jesus-is-presented-at-the-temple":
    "Forty days after Jesus was born, Mary and Joseph brought him to the temple in Jerusalem with the offering of a family that could not afford a lamb. An old man named Simeon, who had been promised he would see the Christ before he died, took Jesus in his arms and praised God for his salvation, a light for every nation. Then Simeon warned Mary of sorrow to come, and Anna, a very old prophetess, thanked God and told everyone waiting for God's rescue about the child.",
  "the-first-disciples":
    "John the Baptist pointed to Jesus and said, \"Look, the Lamb of God!\" and two of his followers went after Jesus, who said, \"Come and see.\" One of them, Andrew, brought his brother Simon, and Jesus named him Cephas, or Peter. The next day Jesus called Philip, and Philip told his doubtful friend Nathanael, who was amazed that Jesus already knew him and called him the Son of God, and Jesus promised they would see heaven open.",
  "peter-says-who-jesus-is":
    "On the road near Caesarea Philippi, Jesus asked his disciples who people said he was, and then who they said he was. Peter answered, \"You are the Christ.\" But when Jesus said he would suffer, be killed, and rise again, Peter scolded him, and Jesus said, \"Get behind Me, Satan!\" Then Jesus told the crowd that anyone who follows him must take up his cross, because whoever loses his life for Jesus and the gospel will save it.",
  "the-transfiguration":
    "Jesus took Peter, James, and John up a high mountain, where his clothes shone whiter than anything on earth, and Moses and Elijah appeared and talked with him. Peter was terrified and offered to build three shelters. Then a cloud covered them, and God's voice said, \"This is My beloved Son. Listen to Him!\" When they looked around, only Jesus was there, and on the way down he told them to tell no one until he had risen from the dead.",
  "the-good-shepherd":
    "Jesus said he is the gate for the sheep and the good shepherd, who calls his sheep by name and lays down his life for them, while a hired hand runs from the wolf. He said no one takes his life from him. He gives it and takes it up again. Months later, in winter, Jesus promised that his sheep listen to his voice, that he gives them eternal life, and that no one can snatch them out of his hand.",
  "paul-in-athens":
    "While Paul waited in Athens, he was upset to see the city full of idols, and philosophers brought him to the council called the Areopagus. Paul pointed to an altar \"to an unknown god\" and told them about the God who made the world, who is not far from anyone, and who proved he will judge the world by raising a man from the dead. Some laughed, some wanted to hear more, and some believed, including Dionysius and a woman named Damaris.",
  "the-shipwreck":
    "Paul sailed for Rome as a prisoner, warned that the voyage would end in disaster, and was ignored. A storm drove the ship for fourteen days until everyone lost hope, but Paul said an angel had promised that all 276 people would live, and when the ship broke apart on Malta, everyone reached land. On Malta a viper bit Paul without harming him, Paul healed the sick, and at last he reached Rome.",
  "paul-and-silas-in-prison":
    "Paul and Silas crossed the sea to Philippi, where a businesswoman named Lydia believed and was baptized. After Paul commanded a fortune-telling spirit to leave a slave girl, her owners had Paul and Silas beaten and jailed, but at midnight they sang hymns, an earthquake opened the doors, and Paul stopped the jailer from killing himself. The jailer and his household believed in Jesus and were baptized that night, and a new church began meeting in Lydia's home.",
  "philippians-1":
    "Paul writes to the church in Philippi from chains, waiting for a trial that could end in his death. He thanks God for them, says his chains have helped the good news spread, and is torn between living and dying, but expects to live. He urges them to stand firm together without fear.",
  "philippians-2":
    "Paul urges the church to be united and to put others first, and points them to Jesus, who emptied himself, died on a cross, and was lifted up by God. He reminds them that God is at work in them and tells them to shine like lights in the world. Then he shares his plans to send Timothy and Epaphroditus.",
  "philippians-3":
    "Paul warns against teachers who said believers had to be circumcised, and lists his own proud record as a Jew and a Pharisee. He says he counts it all as loss next to knowing Christ and receiving the righteousness that comes from God through faith. He presses on toward the goal and reminds them that their citizenship is in heaven.",
  "philippians-4":
    "Paul urges two women in the church to agree, and tells the church to rejoice always and to bring every worry to God with thanks, so God's peace will guard their hearts. He thanks them for their gift and says he has learned to be content in any situation, because he can do all things through Christ who gives him strength. He ends with greetings and grace.",
  "isaiah-40":
    "Isaiah 40 is God's message to his people in exile in Babylon, and its first word is \"Comfort.\" A voice calls for a highway for God across the desert and says people fade like grass, but God's word stands forever. God comes like a shepherd, rules over every nation and star, and gives strength to tired people, so those who wait upon the LORD will mount up with wings like eagles.",
  "the-crucifixion":
    "Jesus was led to a place called the Skull and crucified between two criminals. Jesus prayed for God to forgive the people who did it and promised one criminal he would be with him in paradise. At noon the sky went dark, Jesus died, and Joseph of Arimathea buried him in a tomb.",
  "the-resurrection":
    "Early on Sunday morning, women came to Jesus's tomb and found the stone rolled away and the body gone. Two men in shining clothes told them Jesus was not there, because he had risen. The women told the apostles, and Peter ran to the tomb and saw it was empty.",
  // Batch 14
  "psalm-27":
    "Psalm 27 is a prayer of trust in danger. David's opening line is the whole psalm: the LORD is his light, salvation, and stronghold — whom shall he fear? He asks one thing: to dwell in God's house all his days, see His beauty, and seek shelter in His tent. Even if father and mother abandon him, God will receive him. The psalm ends with a call that has steadied people across the centuries: be strong and courageous — wait for the LORD.",
  "psalm-37":
    "Psalm 37 answers a question that troubles every honest person: why do people who do wrong seem to flourish? Do not fret, says David — their end is coming. He gives five commands: trust, delight, commit, be still, and wait. The righteous may stumble, but the LORD upholds their hand. The meek will inherit the land. The salvation of the righteous is from the LORD; He is their stronghold in time of trouble.",
  "psalm-50":
    "God speaks as judge from Zion — the Mighty One, the LORD, calling the earth to witness. He does not rebuke them for their burnt offerings; He receives them. But He does not need them: He owns every animal in the forest. What He wants is a sacrifice of thanksgiving, a fulfilled vow, a call on His name in trouble. And His promise in return: I will deliver you, and you will honor Me.",
  "psalm-51":
    "David wrote Psalm 51 after Nathan the prophet confronted him about Bathsheba and the murder of Uriah. He does not explain or justify. He asks for mercy on the only ground he sees: God's steadfast love. Three words for what is wrong — transgressions, iniquity, sin — and three for what he needs: blot out, wash, cleanse. The deepest plea is not to escape punishment but to keep God's presence. The sacrifice He will not despise: a broken and a contrite heart.",
  "psalm-66":
    "Psalm 66 opens with a call to all the earth to shout for joy, then moves through community testimony — God refined us like silver, brought us through fire and water to abundance — and ends with one person's private witness: I cried out, He heard, He did not withhold His love. The movement is from creation-wide praise to a single answered prayer. The final word is not doctrine but relief: He heard. He did not turn away.",
  "psalm-67":
    "Psalm 67 is a harvest prayer, seven verses long, that carries the whole Abrahamic promise inside it. The opening echoes the Aaronic blessing of Numbers 6: may God be gracious and cause His face to shine. But the reason for the blessing is the nations — \"that Your ways may be known on earth.\" The refrain appears twice: let all the peoples praise You. The psalm ends where it began: from a harvest prayer to a vision of the whole earth fearing God.",
  "psalm-81":
    "Psalm 81 is a festival psalm that turns into a divine speech. The celebration is commanded — ram's horn, tambourine, harp — and then God's own voice breaks in. He recalls the Exodus: I freed your shoulder from the burden, I answered you from the cloud. And then the staggering offer: I am the LORD your God. Open wide your mouth and I will fill it. But My people would not listen. He gave them over to their stubborn hearts. The psalm ends not with condemnation but with the promise still on the table.",
  "psalm-90":
    "Psalm 90 is Moses's prayer — the oldest in the Psalter. God is from everlasting to everlasting; a thousand years in His sight are like a day. But humans return to dust: they are like grass that flourishes in the morning and fades by evening. Under God's anger, human years end like a sigh. So Moses prays: teach us to number our days. Satisfy us in the morning with Your loving devotion. Let the beauty of the LORD our God rest upon us and establish the work of our hands.",
  "psalm-91":
    "Psalm 91 makes extraordinary promises to the one who makes God their dwelling place. No terror of the night, no arrow by day, no plague at noon — a thousand may fall at your side and ten thousand at your right hand, but it will not come near you. The protection is not magic but relational: he has set his love on Me. The closing verses shift to God's own voice: I will answer when he calls, be with him in trouble, deliver and honor him, and show him my salvation.",
  "psalm-95":
    "Psalm 95 opens with a shout for joy to the Rock of our salvation — He holds the depths of the earth, the peaks, the seas, the dry land. Come and kneel before the LORD our Maker: He is our God and we are the sheep of His pasture. Then the psalm turns: hear His voice today. Do not harden your hearts as at Meribah and Massah, where Israel tested God in the wilderness. The Epistle to the Hebrews quotes this psalm to say that the rest God promised is still open — and still available today.",
  "psalm-98":
    "Psalm 98 calls for a new song because something new has happened: God's right hand and holy arm have won a victory. He has made His salvation known to the nations and remembered His love and faithfulness to Israel. The call goes out to all the earth — to burst into song, make music, shout for joy. And even the sea, the rivers, and the mountains are summoned to join in. He comes to judge the world in righteousness and the peoples with equity.",
  "psalm-99":
    "Psalm 99 declares that the LORD reigns — enthroned above the cherubim, exalted above all nations. His name is great and awesome. He loves justice and has established equity. Three times the refrain rises: He is holy, He is holy, He is holy. Moses and Aaron called His name, and He answered from the cloud. Samuel called, and He answered. He is forgiving — and an avenger of wrongdoing. The psalm calls every generation to exalt and worship.",
  "psalm-107":
    "Psalm 107 opens Book V of the Psalter with a call to give thanks. Then it tells four stories: wanderers in the desert who could not find a city, brought safely to one; prisoners sitting in darkness and chains, brought out by God's word; those who were sick from their own foolishness, healed by a single word; sailors in a storm, stilled to a whisper. In each story the same line appears: they cried to the LORD in their trouble, and He saved them from their distress. Let the redeemed of the LORD say so.",
  "psalm-111":
    "Psalm 111 is an alphabet acrostic: each line begins with the next letter of the Hebrew alphabet, from A to Z. It praises God's works — glorious and majestic, sought by all who delight in them. He is gracious and compassionate. He feeds those who fear Him and remembers His covenant forever. Holy and awesome is His name. The last line is one of the most quoted in wisdom literature: the fear of the LORD is the beginning of wisdom; all who follow His precepts gain rich understanding.",
  "psalm-112":
    "Psalm 112 is the companion to Psalm 111: where Psalm 111 praises God, Psalm 112 describes the person formed by that praise. Blessed is the one who fears the LORD and delights in His commands. Their children are mighty in the land; their righteousness endures forever. They are gracious and compassionate, generous with the poor. When bad news comes, their heart does not fall — it is steadfast, trusting in the LORD. In the end, the wicked see and gnash their teeth, while the righteous remain.",
  "psalm-116":
    "The psalmist was near death — snares of death, pangs of Sheol. He called on the name of the LORD and was saved. Now he asks: what shall I render? His answer is not a list but a posture: lift the cup of salvation, call on the name of the LORD, pay the vows in the presence of all the people. He declares himself God's servant, son of a maidservant whose bonds have been broken. Precious in the LORD's sight is the death of His saints — so His rescue is costly to God, not indifferent.",
  "psalm-121":
    "Psalm 121 is a pilgrimage psalm, sung on the road to Jerusalem. The traveler looks up at the hills and asks: where does my help come from? The answer: from the LORD, Maker of heaven and earth. He will not allow your foot to slip. The Protector of Israel neither slumbers nor sleeps. He is shade on the right hand. He guards from all evil, preserves the soul. The final promise covers everything: the LORD will watch over your coming and going, both now and forevermore.",
  "psalm-126":
    "When the LORD restored the captives of Zion, it felt like a dream — mouths filled with laughter, the nations saying God has done great things for them. But now: restore us again. The prayer for restoration comes with an image of farming in hard soil. Those who sow in tears will reap with shouts of joy. He who goes out weeping, bearing a trail of seed, will surely return carrying sheaves of grain. The weeping and the harvest are not opposites — they belong together.",
  "psalm-130":
    "Psalm 130 is a cry from the lowest place — the depths that gave it its Latin title, De Profundis. If the LORD kept track of iniquities, no one could stand; but with Him is forgiveness, and that forgiveness produces awe. So the psalmist waits, soul engaged, hope placed in God's word — more than watchmen wait for the morning. Then the psalm expands: O Israel, hope in the LORD. With Him is loving devotion and redemption in abundance. He will redeem Israel from all their iniquities.",
  "psalm-131":
    "Psalm 131 is three verses and one of the most tender in the Psalter. David says his heart is not lifted up, his eyes not raised too high — he has not occupied himself with things too great for him. Instead: he has stilled and quieted his soul like a weaned child with its mother. Not a nursing infant demanding to be fed, but a child who has learned to rest simply in the mother's presence. That is the posture he calls Israel to: put your hope in the LORD, both now and forevermore.",
  "would-that-all-were-prophets":
    "Israel grew tired of manna in the wilderness and wept for the food of Egypt. Moses, overwhelmed by the weight of leading them, cried to God that he could not carry these people alone. God answered not by making Moses stronger but by spreading the Spirit across seventy elders. Two of them — Eldad and Medad — received the Spirit outside the tent and prophesied in the camp. Joshua wanted them stopped. Moses said: don't be jealous on my account. I wish all the LORD's people were prophets. That wish came true at Pentecost.",
  "the-manna-stops":
    "After forty years of wilderness wandering, Israel crossed the Jordan into the promised land and camped at Gilgal. There God declared: today I have rolled away the reproach of Egypt from you. They kept the Passover on Canaanite soil for the first time, eating unleavened bread and roasted grain from the produce of the land. The next morning the manna stopped. The daily miracle of bread from heaven had done its work. The land God promised was real enough to eat.",
  "do-not-exalt-yourself":
    "A proverb from Solomon's court, collected by the scribes of King Hezekiah: do not push yourself into the seat of honor in the presence of the king. Do not stand in the place of great men. There are two ways to end up at the head of the table — you can claim a seat and be sent back down in public, or you can wait and be called up. The second is worth more than the first. Jesus told the same story at a dinner party and added: everyone who exalts himself will be humbled, and everyone who humbles himself will be exalted.",
  "elijah-calls-elisha":
    "After his victory on Mount Carmel and his collapse in the wilderness, Elijah received a new task from God: appoint a successor. He found Elisha plowing with twelve teams of oxen — a prosperous farmer with a settled life. Elijah said nothing; he simply threw his cloak over him. Elisha ran after him, asked for a moment to say goodbye, then killed his oxen and burned his plow — no going back. He fed the people, said farewell, and set out to follow and serve Elijah.",
  "elisha-feeds-a-hundred":
    "A man came to Elisha during a famine with twenty loaves of barley bread from the first ripe grain. Elisha told his servant to give it to the hundred men gathered there. The servant saw only the math: twenty loaves for a hundred people is not enough. Elisha repeated the command and added the word of the LORD: they will eat and have some left over. The servant set it before them. They ate and had some left over, according to the word of the LORD.",
  "zion-will-be-plowed":
    "Micah directed his sharpest words at three groups: prophets who declared peace when they were fed and war when they were not, priests who taught for money, and leaders who judged for bribes. All three claimed the LORD was among them and no disaster could touch them. Micah answered with his own authority — filled with power by the Spirit of the LORD, with justice and courage. Because of them, he said, Zion will be plowed like a field, Jerusalem will become a heap of rubble, and the temple mount a high place overgrown with thickets.",
  "the-day-of-the-lord-is-near":
    "Zephaniah called for silence before the Lord GOD: the Day of the LORD is near, and He has prepared a sacrifice. His judgment would fall on the complacent — those who thought God would do nothing, either good or bad. They had settled into their comfort, assuming the silence of heaven meant the absence of God. On that day, Zephaniah warned, neither silver nor gold would save anyone. The whole earth would be consumed by the fire of His jealousy. Yet the very warning was an invitation: be still, and do not treat His silence as indifference.",
};
