/* The Word Bank. One plain meaning per word, used the same way in every
   story (Style Guide v1.1, Part 12). Word help underlines the first time
   a word appears in a story. Tapping it shows this meaning.

   Keep each meaning short: one or two sentences, common words only, so it
   works for young readers and for people still learning English.
   `match` lists the forms to look for in the text, longest first. */

export interface Word { word: string; meaning: string; match: string[] }

export const WORDS: Word[] = [
  { word: "Blessed", meaning: "God's favor rests on them.", match: ["Blessed", "blessed"] },
  { word: "Kingdom of heaven", meaning: "God's rule. The way God runs things. Not only a place after death: it starts wherever Jesus is. Also called the kingdom of God.", match: ["kingdom of heaven", "kingdom of God", "God's kingdom"] },
  { word: "Righteousness", meaning: "Being right with God, and doing what is right and fair. God gives it through Jesus, and then we grow in doing right.", match: ["righteousness"] },
  { word: "Repent", meaning: "Turn back to God. God is the one who turns us.", match: ["Repent", "repent"] },
  { word: "Grace", meaning: "God's love and gifts that we don't earn.", match: ["grace"] },
  { word: "Gospel", meaning: "The good news of what God does for us in Jesus.", match: ["gospel"] },
  { word: "Inherit", meaning: "Receive something as a gift because of whose family you're in.", match: ["inherit"] },
  { word: "Meek", meaning: "Gentle. Not pushy, and not weak.", match: ["meek"] },
  { word: "Mourn", meaning: "Feel deep sadness, often after someone dies.", match: ["mourn"] },
  { word: "Mercy", meaning: "Kindness and help for someone who is hurting or has done wrong.", match: ["merciful", "mercy"] },
  { word: "Persecuted", meaning: "Hurt or treated badly again and again, often because of what you believe.", match: ["persecuted", "persecute"] },
  { word: "Peacemakers", meaning: "People who help others stop fighting.", match: ["peacemakers"] },
  { word: "Hypocrite", meaning: "A pretender. The Greek word meant a stage actor.", match: ["hypocrite"] },
  { word: "Scribes", meaning: "Teachers of Moses's law.", match: ["scribes"] },
  { word: "Pharisees", meaning: "A Jewish group devoted to carefully keeping God's law.", match: ["Pharisees"] },
  { word: "Synagogue", meaning: "A local meeting place for Jewish worship and study.", match: ["synagogues", "synagogue"] },
  { word: "Disciples", meaning: "Followers who learn from a teacher. Jesus's disciples followed him everywhere.", match: ["disciples"] },
  { word: "Prophet", meaning: "Someone God sends to speak God's message.", match: ["prophets", "prophet"] },
  { word: "Messiah", meaning: "The anointed one: the king God promised to send. In Greek, the word is Christ.", match: ["Messiah"] },
  { word: "LORD", meaning: "LORD in capital letters stands for God's personal name. Jewish readers traditionally don't say it aloud, out of respect.", match: ["LORD"] },
  { word: "LORD of Hosts", meaning: "The Lord of armies. God commands the armies of heaven.", match: ["LORD of Hosts"] },
  { word: "Anoint", meaning: "Pour oil on someone to show God has chosen them.", match: ["anointed", "anoint"] },
  { word: "Philistines", meaning: "A people who lived near the sea, west of Israel. They were often at war with Israel.", match: ["Philistines", "Philistine"] },
  { word: "Salvation", meaning: "Being rescued by God.", match: ["Salvation", "salvation"] },
  { word: "Eternal life", meaning: "Life with God that never ends.", match: ["eternal life"] },
  { word: "Parable", meaning: "A short story Jesus told to teach something. The people in it are made up, but the point is real.", match: ["parable"] },
  { word: "Samaritans", meaning: "People from Samaria, north of Jerusalem. Jewish people and Samaritans had distrusted each other for centuries.", match: ["Samaritans", "Samaritan"] },
  { word: "Levite", meaning: "A helper at God's temple, from the family of Levi.", match: ["Levites", "Levite"] },
  { word: "Tax collectors", meaning: "People who collected money for the Roman rulers. Many took extra for themselves, so people saw them as cheats.", match: ["tax collectors", "tax collector"] },
  { word: "Son of Man", meaning: "A name Jesus often used for himself.", match: ["Son of Man"] },
  { word: "Compassion", meaning: "Caring deeply about someone who hurts, enough to help.", match: ["compassionate", "compassion"] },
  { word: "Sackcloth", meaning: "Rough cloth people wore to show they were sorry or sad.", match: ["sackcloth"] },
  { word: "Crucify", meaning: "To nail someone to a wooden cross and leave them to die. It was one of Rome's cruelest punishments.", match: ["crucified", "crucify"] },
  { word: "Paradise", meaning: "Being with God.", match: ["Paradise"] },
  { word: "Apostles", meaning: "Jesus's closest followers, the ones he sent out to tell others about him.", match: ["apostles"] },
  { word: "Sabbath", meaning: "The weekly day of rest, from Friday sunset to Saturday sunset.", match: ["Sabbath"] },
  { word: "Sin", meaning: "Turning away from God and hurting others or ourselves. Also the broken part of us that keeps doing it.", match: ["sins", "sinful", "sin"] },
  { word: "Faith", meaning: "Trusting God. Faith is a gift God gives, not something we make ourselves.", match: ["faith"] },
  { word: "Savior", meaning: "Someone who rescues. Christians call Jesus the Savior.", match: ["Savior"] },
  { word: "Risen", meaning: "Raised from the dead. God raised Jesus to a new life that never ends.", match: ["risen"] },
  { word: "Baptism", meaning: "Being washed with water in God's name. In Baptism, God makes you his own child.", match: ["Baptism", "baptized"] },
  { word: "Holy Spirit", meaning: "God's Spirit, who gives faith, brings comfort, and helps us live as God's people.", match: ["Holy Spirit", "Spirit of the LORD"] },
  { word: "Law", meaning: "God's commands, given through Moses. They show us how to live and where we fall short.", match: ["Moses's law", "God's law"] },
  { word: "Cast lots", meaning: "Throwing marked stones or sticks to choose or decide something.", match: ["cast lots", "casting lots", "Casting lots"] },
  { word: "Circumcision", meaning: "A sign, done to Jewish baby boys, that they belong to God's people and his promise.", match: ["uncircumcised", "circumcised", "Circumcision", "circumcision"] },
  { word: "Cubit", meaning: "An old measure, about 18 inches: the length from your elbow to your fingertips.", match: ["cubits", "cubit"] },
  { word: "Lectionary", meaning: "A plan for which Bible passages churches read each Sunday.", match: ["Lectionary", "lectionary"] },
  { word: "Year A, B, C", meaning: "The Sunday reading plan repeats every three years. The years are called A, B, and C.", match: ["Year A", "Year B", "Year C"] },
  { word: "Epiphany", meaning: "A church season in January and February about Jesus being shown to the world.", match: ["Epiphany"] },
  { word: "ELCA", meaning: "The Evangelical Lutheran Church in America.", match: ["ELCA"] },
  { word: "Josephus", meaning: "A Jewish historian who wrote about 60 years after Jesus.", match: ["Josephus"] },
  { word: "Image of God", meaning: "Made to reflect God in a way nothing else does. The Bible says this is true of every person.", match: ["image of God", "God's image", "His own image"] },
  { word: "Eden", meaning: "The place where God planted the first garden.", match: ["Eden"] },
  { word: "Serpent", meaning: "An old word for a snake.", match: ["serpent"] },
  { word: "Cherubim", meaning: "Powerful heavenly beings who guard God's holy places.", match: ["cherubim"] },
  { word: "Trinity", meaning: "One God in three persons: the Father, the Son, and the Holy Spirit.", match: ["Trinity"] },
  { word: "Ash Wednesday", meaning: "The first day of Lent. Many churches mark a cross of ashes on people's foreheads.", match: ["Ash Wednesday"] },
  { word: "Lent", meaning: "The 40 days before Easter, a time to turn back to God.", match: ["Lent"] },
  { word: "Pharaoh", meaning: "The title for the king of Egypt.", match: ["Pharaoh"] },
  { word: "Passover", meaning: "The night God passed over the Israelites' homes and set them free. Jewish families still celebrate it every year.", match: ["Passover"] },
  { word: "Plague", meaning: "A disaster that hurts a whole land.", match: ["plagues", "plague"] },
  { word: "Israelites", meaning: "God's people, the family of Abraham, Isaac, and Jacob. Jacob was also called Israel.", match: ["Israelites"] },
  { word: "Hebrews", meaning: "Another name for the Israelites.", match: ["Hebrews", "Hebrew"] },
  { word: "Covenant", meaning: "A promise that binds two sides together. God makes covenants with his people and keeps them.", match: ["covenant"] },
  { word: "Holy", meaning: "Set apart for God.", match: ["Holy", "holy"] },
  { word: "Maundy Thursday", meaning: "The Thursday before Easter, when Christians remember Jesus's Last Supper.", match: ["Maundy Thursday"] },
  { word: "Pentecost", meaning: "A Jewish harvest festival, 50 days after Passover. Christians remember it as the day the Holy Spirit came.", match: ["Pentecost"] },
  { word: "Witness", meaning: "Someone who saw something happen and tells about it.", match: ["witnesses", "witness"] },
  { word: "Galileans", meaning: "People from Galilee, the area in northern Israel where Jesus grew up.", match: ["Galileans"] },
  { word: "Centurion", meaning: "A Roman army officer in charge of about 100 soldiers.", match: ["centurion"] },
  /* Added September 2026 with the first 20 new stories. */
  { word: "Ark", meaning: "A huge wooden box that floats, like a giant boat. God told Noah to build one.", match: ["ark"] },
  { word: "Altar", meaning: "A raised place, often made of stones, where people gave offerings to God.", match: ["altars", "altar"] },
  { word: "Burnt offering", meaning: "A gift to God, usually an animal, burned whole on an altar.", match: ["burnt offerings", "burnt offering"] },
  { word: "Righteous", meaning: "Right with God. God makes people right with him, and they grow in doing what is right.", match: ["righteous"] },
  { word: "Famine", meaning: "A long time when there is not enough food for people to eat.", match: ["famines", "famine"] },
  { word: "Cupbearer", meaning: "An officer who served the king his wine. It was a trusted, high job.", match: ["cupbearers", "cupbearer"] },
  { word: "Interpretation", meaning: "An explanation of what something means, like a dream.", match: ["interpretations", "interpretation", "interpret"] },
  { word: "Signet ring", meaning: "A ring with the king's seal on it. Pressing it into wax or clay made an order official.", match: ["signet ring", "signet"] },
  { word: "Covet", meaning: "To want something that belongs to someone else so much that you would take it from them.", match: ["covet"] },
  { word: "Idol", meaning: "A statue or picture that people worship as a god. Anything we trust more than God can become an idol.", match: ["idols", "idol"] },
  { word: "Adultery", meaning: "Breaking a marriage promise by having sex with someone who is not your husband or wife.", match: ["adultery"] },
  { word: "Consecrate", meaning: "To get ready and be set apart for God.", match: ["consecrate"] },
  { word: "Glean", meaning: "To pick up the grain that harvest workers leave behind. God's law told farmers to leave some for the poor and for foreigners.", match: ["gleaning", "gleaned", "glean"] },
  { word: "Kinsman-redeemer", meaning: "A close relative with a duty to rescue family in trouble. He could buy back family land or help keep a family's name alive.", match: ["kinsman-redeemers", "kinsman-redeemer"] },
  { word: "Hesed", meaning: "A Hebrew word for loyal, faithful love. It is love that keeps its promises and stays.", match: ["hesed"] },
  { word: "Widow", meaning: "A woman whose husband has died.", match: ["widows", "widow"] },
  { word: "Psalm", meaning: "A song or prayer from the Bible's book of Psalms. There are 150 of them.", match: ["Psalms", "psalms", "Psalm", "psalm"] },
  { word: "Pasture", meaning: "A field of grass where sheep and other animals eat.", match: ["pastures", "pasture"] },
  { word: "Restore", meaning: "To make something new or whole again.", match: ["restoring", "restores", "restored", "restore"] },
  { word: "Dwell", meaning: "To live somewhere. To make your home there.", match: ["dwelling", "dwells", "dwell"] },
  { word: "Exile", meaning: "Being forced to live far from your homeland. Babylon took many of Judah's people into exile.", match: ["exiles", "exile", "Exile"] },
  { word: "Astrologers", meaning: "People who study the stars to try to tell the future.", match: ["astrologers", "Astrologers", "astrologer"] },
  { word: "Apocrypha", meaning: "Old Jewish books found in some Bibles. Catholic and Orthodox Christians count them as Scripture. Lutherans read them as useful but not equal to Scripture.", match: ["Apocrypha", "apocrypha"] },
  { word: "Satrap", meaning: "A governor who ruled one part of the Persian kingdom for the king.", match: ["satraps", "Satraps", "satrap", "Satrap"] },
  { word: "Angel", meaning: "A messenger from God.", match: ["angel", "Angel"] },
  { word: "Magi", meaning: "Wise men from the east who studied the stars. They often advised kings.", match: ["Magi"] },
  { word: "Frankincense", meaning: "Sweet-smelling dried tree sap. People burned it in worship.", match: ["frankincense"] },
  { word: "Myrrh", meaning: "Dried tree sap. It was used in perfume and to prepare a body for burial.", match: ["myrrh"] },
  { word: "Refugee", meaning: "Someone who must leave home to stay safe.", match: ["refugees", "refugee"] },
  { word: "Sign", meaning: "Something that points to something bigger. In John's Gospel, Jesus's miracles are called signs because they show who he is.", match: ["signs", "sign"] },
  { word: "Glory", meaning: "The shining greatness of God. In Jesus, people could see it up close.", match: ["glory"] },
  { word: "Master of the banquet", meaning: "The man in charge of a feast. He made sure the food and drink were served well.", match: ["master of the banquet"] },
  { word: "Bridegroom", meaning: "The man getting married.", match: ["bridegroom"] },
  { word: "Rabbi", meaning: "A Hebrew word that means \"teacher.\" People used it for respected teachers of God's law.", match: ["Rabbi", "rabbi"] },
  { word: "Born again", meaning: "A new birth that God gives by the Holy Spirit. The Greek word can mean \"again\" or \"from above.\"", match: ["born again", "Born again", "new birth"] },
  { word: "Condemn", meaning: "To judge someone guilty and punish them. Jesus came to save, not to condemn.", match: ["condemned", "condemn", "Condemn"] },
  { word: "Living water", meaning: "Fresh water that flows from a spring or stream. Jesus used it as a comparison for the life God gives.", match: ["living water"] },
  { word: "Worship", meaning: "Honoring God with prayer, praise, and our whole lives.", match: ["worshiped", "worship"] },
  { word: "Harvest", meaning: "The time when grain is ready to cut and gather.", match: ["harvest"] },
  { word: "Hallowed", meaning: "Treated as holy. Honored as set apart for God.", match: ["hallowed", "Hallowed"] },
  { word: "Temptation", meaning: "A pull toward doing something wrong.", match: ["temptation", "tempted", "tempt"] },
  { word: "Trespasses", meaning: "Wrongs. The times someone crosses a line and hurts another person.", match: ["trespasses", "trespass"] },
  { word: "Pagans", meaning: "In the Bible, people who worshiped other gods, not the God of Israel.", match: ["pagans", "Pagans"] },
  { word: "Sow", meaning: "Scatter seed on the ground so it can grow.", match: ["sowing", "sowed", "sows", "sow"] },
  { word: "Mystery", meaning: "In the Bible, something hidden that God shows to people. Not a puzzle to solve.", match: ["mystery"] },
  { word: "Satan", meaning: "The enemy of God. Jesus came to defeat him.", match: ["Satan"] },
  { word: "Means of grace", meaning: "The ways God comes to us with forgiveness and faith: his word, Baptism, and the Lord's Supper.", match: ["means of grace"] },
  { word: "Denarius", meaning: "A Roman silver coin. It was about one day's pay for a worker. More than one are called denarii.", match: ["denarius", "denarii"] },
  { word: "Barley", meaning: "A grain like wheat. Barley bread was a common, simple food.", match: ["barley"] },
  { word: "Lord's Supper", meaning: "The meal Jesus gave his followers the night before he died. Christians share bread and wine in it. Also called Communion.", match: ["Lord's Supper"] },
  { word: "Fourth watch", meaning: "The last part of the night, about 3 to 6 in the morning. A watch was the time one guard stayed on duty.", match: ["fourth watch"] },
  { word: "Son of God", meaning: "A title for Jesus. Christians believe it means he shares God's own life and is God with us.", match: ["beloved Son", "Son of God"] },
  { word: "I AM", meaning: "A name God gave for himself when he spoke to Moses (Exodus 3:14). It means God always is.", match: ["I AM WHO I AM", "I AM"] },
  { word: "Prodigal", meaning: "Wasteful. Someone who spends everything carelessly.", match: ["prodigal"] },
  { word: "Squandered", meaning: "Wasted. Used up carelessly until nothing was left.", match: ["squandered", "squander"] },
  { word: "Unclean", meaning: "In Moses's law, something God's people were not to eat or touch, or that kept a person from worship for a time.", match: ["unclean"] },
  { word: "Resurrection", meaning: "Coming back to life after death, never to die again. Christians believe God will raise the dead on the last day.", match: ["resurrection", "Resurrection"] },
  { word: "Mourners", meaning: "People who come to cry with a family after someone dies.", match: ["mourners", "Mourners", "mourning", "Mourning"] },
  { word: "Linen", meaning: "Cloth made from a plant called flax. Back then, the dead were wrapped in strips of it.", match: ["linen", "Linen"] },
  { word: "Unleavened", meaning: "Made without yeast, so the bread stays flat. Israel ate it at the first Passover because they left Egypt in a hurry.", match: ["Unleavened", "unleavened"] },
  { word: "Gentiles", meaning: "People who are not Jewish.", match: ["Gentiles", "Gentile"] },
  { word: "Betray", meaning: "To turn against someone who trusted you. Judas handed Jesus over to the people who wanted to arrest him.", match: ["betraying", "betrayed", "betrayer", "betrays", "betray"] },
  { word: "Legion", meaning: "A large unit of the Roman army. In Jesus's day it was about 6,000 soldiers.", match: ["legions", "legion"] },
  { word: "High priest", meaning: "The chief leader of the temple in Jerusalem.", match: ["high priest's", "high priest"] },
  { word: "Deny", meaning: "To say something is not true. Peter denied Jesus by saying he did not know him.", match: ["denied", "denies", "denial", "deny"] },
  { word: "Courtyard", meaning: "An open space inside the walls of a big house, with no roof.", match: ["courtyards", "courtyard"] },
  { word: "Condemnation", meaning: "Being judged guilty and sent away. In Jesus, God does not condemn his people.", match: ["condemnation"] },
];
