/* The Word Bank. One plain meaning per word, used the same way in every
   story (Style Guide v1.1, Part 12). Word help underlines the first time
   a word appears in a story. Tapping it shows this meaning.

   Keep each meaning short: one or two sentences, common words only, so it
   works for young readers and for people still learning English.
   `match` lists the forms to look for in the text, longest first. */

export interface Word { word: string; meaning: string; match: string[] }

export const WORDS: Word[] = [
  { word: "Blessed", meaning: "God's favor rests on them.", match: ["Blessed", "blessed"] },
  { word: "Kingdom of heaven", meaning: "God's rule. The way God runs things. Not only a place after death: it starts wherever Jesus is. Also called the kingdom of God.", match: ["kingdom of heaven", "kingdom of God", "God's kingdom"] },
  { word: "Righteousness", meaning: "Being right with God, and doing what is right and fair. God gives it through Jesus, and then we grow in doing right.", match: ["righteousness"] },
  { word: "Repent", meaning: "Turn back to God. God is the one who turns us.", match: ["Repent", "repent"] },
  { word: "Grace", meaning: "God's love and gifts that we don't earn.", match: ["grace"] },
  { word: "Gospel", meaning: "The good news of what God does for us in Jesus.", match: ["gospel"] },
  { word: "Inherit", meaning: "Receive something as a gift because of whose family you're in.", match: ["inherit"] },
  { word: "Meek", meaning: "Gentle. Not pushy, and not weak.", match: ["meek"] },
  { word: "Mourn", meaning: "Feel deep sadness, often after someone dies.", match: ["mourn"] },
  { word: "Mercy", meaning: "Kindness and help for someone who is hurting or has done wrong.", match: ["merciful", "mercy"] },
  { word: "Persecuted", meaning: "Hurt or treated badly again and again, often because of what you believe.", match: ["persecuted", "persecute"] },
  { word: "Peacemakers", meaning: "People who help others stop fighting.", match: ["peacemakers"] },
  { word: "Hypocrite", meaning: "A pretender. The Greek word meant a stage actor.", match: ["hypocrite"] },
  { word: "Scribes", meaning: "Teachers of Moses's law.", match: ["scribes"] },
  { word: "Pharisees", meaning: "A Jewish group devoted to carefully keeping God's law.", match: ["Pharisees"] },
  { word: "Synagogue", meaning: "A local meeting place for Jewish worship and study.", match: ["synagogues", "synagogue"] },
  { word: "Disciples", meaning: "Followers who learn from a teacher. Jesus's disciples followed him everywhere.", match: ["disciples"] },
  { word: "Prophet", meaning: "Someone God sends to speak God's message.", match: ["prophets", "prophet"] },
  { word: "Messiah", meaning: "The anointed one: the king God promised to send. In Greek, the word is Christ.", match: ["Messiah"] },
  { word: "LORD", meaning: "LORD in capital letters stands for God's personal name. Jewish readers traditionally don't say it aloud, out of respect.", match: ["LORD"] },
  { word: "LORD of Hosts", meaning: "The Lord of armies. God commands the armies of heaven.", match: ["LORD of Hosts"] },
  { word: "Anoint", meaning: "Pour oil on someone to show God has chosen them.", match: ["anointed", "anoint"] },
  { word: "Philistines", meaning: "A people who lived near the sea, west of Israel. They were often at war with Israel.", match: ["Philistines", "Philistine"] },
  { word: "Salvation", meaning: "Being rescued by God.", match: ["Salvation", "salvation"] },
  { word: "Eternal life", meaning: "Life with God that never ends.", match: ["eternal life"] },
  { word: "Parable", meaning: "A short story Jesus told to teach something. The people in it are made up, but the point is real.", match: ["parable"] },
  { word: "Samaritans", meaning: "People from Samaria, north of Jerusalem. Jewish people and Samaritans had distrusted each other for centuries.", match: ["Samaritans", "Samaritan"] },
  { word: "Levite", meaning: "A helper at God's temple, from the family of Levi.", match: ["Levites", "Levite"] },
  { word: "Tax collectors", meaning: "People who collected money for the Roman rulers. Many took extra for themselves, so people saw them as cheats.", match: ["tax collectors", "tax collector"] },
  { word: "Son of Man", meaning: "A name Jesus often used for himself.", match: ["Son of Man"] },
  { word: "Compassion", meaning: "Caring deeply about someone who hurts, enough to help.", match: ["compassionate", "compassion"] },
  { word: "Sackcloth", meaning: "Rough cloth people wore to show they were sorry or sad.", match: ["sackcloth"] },
  { word: "Crucify", meaning: "To nail someone to a wooden cross and leave them to die. It was one of Rome's cruelest punishments.", match: ["crucified", "crucify"] },
  { word: "Paradise", meaning: "Being with God.", match: ["Paradise"] },
  { word: "Apostles", meaning: "Jesus's closest followers, the ones he sent out to tell others about him.", match: ["apostles"] },
  { word: "Sabbath", meaning: "The weekly day of rest, from Friday sunset to Saturday sunset.", match: ["Sabbath"] },
  { word: "Sin", meaning: "Turning away from God and hurting others or ourselves. Also the broken part of us that keeps doing it.", match: ["sins", "sinful", "sin"] },
  { word: "Faith", meaning: "Trusting God. Faith is a gift God gives, not something we make ourselves.", match: ["faith"] },
  { word: "Savior", meaning: "Someone who rescues. Christians call Jesus the Savior.", match: ["Savior"] },
  { word: "Risen", meaning: "Raised from the dead. God raised Jesus to a new life that never ends.", match: ["risen"] },
  { word: "Baptism", meaning: "Being washed with water in God's name. In Baptism, God makes you his own child.", match: ["Baptism", "baptized"] },
  { word: "Holy Spirit", meaning: "God's Spirit, who gives faith, brings comfort, and helps us live as God's people.", match: ["Holy Spirit", "Spirit of the LORD"] },
  { word: "Law", meaning: "God's commands, given through Moses. They show us how to live and where we fall short.", match: ["Moses's law", "God's law"] },
  { word: "Cast lots", meaning: "Throwing marked stones or sticks to choose or decide something.", match: ["cast lots", "casting lots", "Casting lots"] },
  { word: "Circumcision", meaning: "A sign, done to Jewish baby boys, that they belong to God's people and his promise.", match: ["uncircumcised", "circumcised", "Circumcision", "circumcision"] },
  { word: "Cubit", meaning: "An old measure, about 18 inches: the length from your elbow to your fingertips.", match: ["cubits", "cubit"] },
  { word: "Lectionary", meaning: "A plan for which Bible passages churches read each Sunday.", match: ["Lectionary", "lectionary"] },
  { word: "Year A, B, C", meaning: "The Sunday reading plan repeats every three years. The years are called A, B, and C.", match: ["Year A", "Year B", "Year C"] },
  { word: "Epiphany", meaning: "A church season in January and February about Jesus being shown to the world.", match: ["Epiphany"] },
  { word: "ELCA", meaning: "The Evangelical Lutheran Church in America.", match: ["ELCA"] },
  { word: "Josephus", meaning: "A Jewish historian who wrote about 60 years after Jesus.", match: ["Josephus"] },
  { word: "Image of God", meaning: "Made to reflect God in a way nothing else does. The Bible says this is true of every person.", match: ["image of God", "God's image", "His own image"] },
  { word: "Eden", meaning: "The place where God planted the first garden.", match: ["Eden"] },
  { word: "Serpent", meaning: "An old word for a snake.", match: ["serpent"] },
  { word: "Cherubim", meaning: "Powerful heavenly beings who guard God's holy places.", match: ["cherubim"] },
  { word: "Trinity", meaning: "One God in three persons: the Father, the Son, and the Holy Spirit.", match: ["Trinity"] },
  { word: "Ash Wednesday", meaning: "The first day of Lent. Many churches mark a cross of ashes on people's foreheads.", match: ["Ash Wednesday"] },
  { word: "Lent", meaning: "The 40 days before Easter, a time to turn back to God.", match: ["Lent"] },
  { word: "Pharaoh", meaning: "The title for the king of Egypt.", match: ["Pharaoh"] },
  { word: "Passover", meaning: "The night God passed over the Israelites' homes and set them free. Jewish families still celebrate it every year.", match: ["Passover"] },
  { word: "Plague", meaning: "A disaster that hurts a whole land.", match: ["plagues", "plague"] },
  { word: "Israelites", meaning: "God's people, the family of Abraham, Isaac, and Jacob. Jacob was also called Israel.", match: ["Israelites"] },
  { word: "Hebrews", meaning: "Another name for the Israelites.", match: ["Hebrews", "Hebrew"] },
  { word: "Covenant", meaning: "A promise that binds two sides together. God makes covenants with his people and keeps them.", match: ["covenant"] },
  { word: "Holy", meaning: "Set apart for God.", match: ["Holy", "holy"] },
  { word: "Maundy Thursday", meaning: "The Thursday before Easter, when Christians remember Jesus's Last Supper.", match: ["Maundy Thursday"] },
  { word: "Pentecost", meaning: "A Jewish harvest festival, 50 days after Passover. Christians remember it as the day the Holy Spirit came.", match: ["Pentecost"] },
  { word: "Witness", meaning: "Someone who saw something happen and tells about it.", match: ["witnesses", "witness"] },
  { word: "Galileans", meaning: "People from Galilee, the area in northern Israel where Jesus grew up.", match: ["Galileans"] },
  { word: "Centurion", meaning: "A Roman army officer in charge of about 100 soldiers.", match: ["centurion"] },
  /* Added September 2026 with the first 20 new stories. */
  { word: "Ark", meaning: "A large wooden chest or box. Noah's ark was a huge boat shaped like a box. The ark of the covenant was a sacred chest that held the stone tablets of God's law.", match: ["ark"] },
  { word: "Altar", meaning: "A raised place, often made of stones, where people gave offerings to God.", match: ["altars", "altar"] },
  { word: "Burnt offering", meaning: "A gift to God, usually an animal, burned whole on an altar.", match: ["burnt offerings", "burnt offering"] },
  { word: "Righteous", meaning: "Right with God. God makes people right with him, and they grow in doing what is right.", match: ["righteous"] },
  { word: "Famine", meaning: "A long time when there is not enough food for people to eat.", match: ["famines", "famine"] },
  { word: "Cupbearer", meaning: "An officer who served the king his wine. It was a trusted, high job.", match: ["cupbearers", "cupbearer"] },
  { word: "Interpretation", meaning: "An explanation of what something means, like a dream.", match: ["interpretations", "interpretation", "interpret"] },
  { word: "Signet ring", meaning: "A ring with the king's seal on it. Pressing it into wax or clay made an order official.", match: ["signet ring", "signet"] },
  { word: "Covet", meaning: "To want something that belongs to someone else so much that you would take it from them.", match: ["covet"] },
  { word: "Idol", meaning: "A statue or picture that people worship as a god. Anything we trust more than God can become an idol.", match: ["idols", "idol"] },
  { word: "Adultery", meaning: "Breaking a marriage promise by having sex with someone who is not your husband or wife.", match: ["adultery"] },
  { word: "Consecrate", meaning: "To get ready and be set apart for God.", match: ["consecrate"] },
  { word: "Glean", meaning: "To pick up the grain that harvest workers leave behind. God's law told farmers to leave some for the poor and for foreigners.", match: ["gleaning", "gleaned", "glean"] },
  { word: "Kinsman-redeemer", meaning: "A close relative with a duty to rescue family in trouble. He could buy back family land or help keep a family's name alive.", match: ["kinsman-redeemers", "kinsman-redeemer"] },
  { word: "Hesed", meaning: "A Hebrew word for loyal, faithful love. It is love that keeps its promises and stays.", match: ["hesed"] },
  { word: "Widow", meaning: "A woman whose husband has died.", match: ["widows", "widow"] },
  { word: "Psalm", meaning: "A song or prayer from the Bible's book of Psalms. There are 150 of them.", match: ["Psalms", "psalms", "Psalm", "psalm"] },
  { word: "Pasture", meaning: "A field of grass where sheep and other animals eat.", match: ["pastures", "pasture"] },
  { word: "Restore", meaning: "To make something new or whole again.", match: ["restoring", "restores", "restored", "restore"] },
  { word: "Dwell", meaning: "To live somewhere. To make your home there.", match: ["dwelling", "dwells", "dwell"] },
  { word: "Exile", meaning: "Being forced to live far from your homeland. Babylon took many of Judah's people into exile.", match: ["exiles", "exile", "Exile"] },
  { word: "Astrologers", meaning: "People who study the stars to try to tell the future.", match: ["astrologers", "Astrologers", "astrologer"] },
  { word: "Apocrypha", meaning: "Old Jewish books found in some Bibles. Catholic and Orthodox Christians count them as Scripture. Lutherans read them as useful but not equal to Scripture.", match: ["Apocrypha", "apocrypha"] },
  { word: "Satrap", meaning: "A governor who ruled one part of the Persian kingdom for the king.", match: ["satraps", "Satraps", "satrap", "Satrap"] },
  { word: "Angel", meaning: "A messenger from God.", match: ["angel", "Angel"] },
  { word: "Magi", meaning: "Wise men from the east who studied the stars. They often advised kings.", match: ["Magi"] },
  { word: "Frankincense", meaning: "Sweet-smelling dried tree sap. People burned it in worship.", match: ["frankincense"] },
  { word: "Myrrh", meaning: "Dried tree sap. It was used in perfume and to prepare a body for burial.", match: ["myrrh"] },
  { word: "Refugee", meaning: "Someone who must leave home to stay safe.", match: ["refugees", "refugee"] },
  { word: "Sign", meaning: "Something that points to something bigger. In John's Gospel, Jesus's miracles are called signs because they show who he is.", match: ["signs", "sign"] },
  { word: "Glory", meaning: "The shining greatness of God. In Jesus, people could see it up close.", match: ["glory"] },
  { word: "Master of the banquet", meaning: "The man in charge of a feast. He made sure the food and drink were served well.", match: ["master of the banquet"] },
  { word: "Bridegroom", meaning: "The man getting married.", match: ["bridegroom"] },
  { word: "Rabbi", meaning: "A Hebrew word that means \"teacher.\" People used it for respected teachers of God's law.", match: ["Rabbi", "rabbi"] },
  { word: "Born again", meaning: "A new birth that God gives by the Holy Spirit. The Greek word can mean \"again\" or \"from above.\"", match: ["born again", "Born again", "new birth"] },
  { word: "Condemn", meaning: "To judge someone guilty and punish them. Jesus came to save, not to condemn.", match: ["condemned", "condemn", "Condemn"] },
  { word: "Living water", meaning: "Fresh water that flows from a spring or stream. Jesus used it as a comparison for the life God gives.", match: ["living water"] },
  { word: "Worship", meaning: "Honoring God with prayer, praise, and our whole lives.", match: ["worshiped", "worship"] },
  { word: "Harvest", meaning: "The time when grain is ready to cut and gather.", match: ["harvest"] },
  { word: "Hallowed", meaning: "Treated as holy. Honored as set apart for God.", match: ["hallowed", "Hallowed"] },
  { word: "Temptation", meaning: "A pull toward doing something wrong.", match: ["temptation", "tempted", "tempt"] },
  { word: "Trespasses", meaning: "Wrongs. The times someone crosses a line and hurts another person.", match: ["trespasses", "trespass"] },
  { word: "Pagans", meaning: "In the Bible, people who worshiped other gods, not the God of Israel.", match: ["pagans", "Pagans"] },
  { word: "Sow", meaning: "Scatter seed on the ground so it can grow.", match: ["sowing", "sowed", "sows", "sow"] },
  { word: "Mystery", meaning: "In the Bible, something hidden that God shows to people. Not a puzzle to solve.", match: ["mystery"] },
  { word: "Satan", meaning: "The enemy of God. Jesus came to defeat him.", match: ["Satan"] },
  { word: "Means of grace", meaning: "The ways God comes to us with forgiveness and faith: his word, Baptism, and the Lord's Supper.", match: ["means of grace"] },
  { word: "Denarius", meaning: "A Roman silver coin. It was about one day's pay for a worker. More than one are called denarii.", match: ["denarius", "denarii"] },
  { word: "Barley", meaning: "A grain like wheat. Barley bread was a common, simple food.", match: ["barley"] },
  { word: "Lord's Supper", meaning: "The meal Jesus gave his followers the night before he died. Christians share bread and wine in it. Also called Communion.", match: ["Lord's Supper"] },
  { word: "Fourth watch", meaning: "The last part of the night, about 3 to 6 in the morning. A watch was the time one guard stayed on duty.", match: ["fourth watch"] },
  { word: "Son of God", meaning: "A title for Jesus. Christians believe it means he shares God's own life and is God with us.", match: ["beloved Son", "Son of God"] },
  { word: "I AM", meaning: "A name God gave for himself when he spoke to Moses (Exodus 3:14). It means God always is.", match: ["I AM WHO I AM", "I AM"] },
  { word: "Prodigal", meaning: "Wasteful. Someone who spends everything carelessly.", match: ["prodigal"] },
  { word: "Squandered", meaning: "Wasted. Used up carelessly until nothing was left.", match: ["squandered", "squander"] },
  { word: "Unclean", meaning: "In Moses's law, something God's people were not to eat or touch, or that kept a person from worship for a time.", match: ["unclean"] },
  { word: "Resurrection", meaning: "Coming back to life after death, never to die again. Christians believe God will raise the dead on the last day.", match: ["resurrection", "Resurrection"] },
  { word: "Mourners", meaning: "People who come to cry with a family after someone dies.", match: ["mourners", "Mourners", "mourning", "Mourning"] },
  { word: "Linen", meaning: "Cloth made from a plant called flax. Back then, the dead were wrapped in strips of it.", match: ["linen", "Linen"] },
  { word: "Unleavened", meaning: "Made without yeast, so the bread stays flat. Israel ate it at the first Passover because they left Egypt in a hurry.", match: ["Unleavened", "unleavened"] },
  { word: "Gentiles", meaning: "People who are not Jewish.", match: ["Gentiles", "Gentile"] },
  { word: "Betray", meaning: "To turn against someone who trusted you. Judas handed Jesus over to the people who wanted to arrest him.", match: ["betraying", "betrayed", "betrayer", "betrays", "betray"] },
  { word: "Legion", meaning: "A large unit of the Roman army. In Jesus's day it was about 6,000 soldiers.", match: ["legions", "legion"] },
  { word: "High priest", meaning: "The chief leader of the temple in Jerusalem.", match: ["high priest's", "high priest"] },
  { word: "Deny", meaning: "To say something is not true. Peter denied Jesus by saying he did not know him.", match: ["denied", "denies", "denial", "deny"] },
  { word: "Courtyard", meaning: "An open space inside the walls of a big house, with no roof.", match: ["courtyards", "courtyard"] },
  { word: "Condemnation", meaning: "Being judged guilty and sent away. In Jesus, God does not condemn his people.", match: ["condemnation"] },
  { word: "Sanhedrin", meaning: "The highest Jewish council in Jerusalem. It was led by the high priest.", match: ["Sanhedrin"] },
  { word: "Governor", meaning: "A ruler sent by Rome to run a province. Pilate was the Roman governor of Judea.", match: ["governors", "governor"] },
  { word: "Mock", meaning: "To make fun of someone in a cruel way.", match: ["mocking", "mocked", "mocks", "mock"] },
  { word: "Rebellion", meaning: "A violent fight against the people in charge.", match: ["rebellions", "rebellion"] },
  { word: "Tomb", meaning: "A place where a dead body is laid. In Jesus's day, many tombs were rooms cut into rock.", match: ["tombs", "tomb"] },
  { word: "Council", meaning: "A group of Jewish leaders in Jerusalem who made decisions for the people.", match: ["council"] },
  { word: "Preparation Day", meaning: "Friday, the day people got ready for the Sabbath.", match: ["Preparation Day"] },
  { word: "Spices", meaning: "Sweet-smelling plants and oils. People used them to care for a body after death.", match: ["spices", "spice"] },
  { word: "Dawn", meaning: "The first light of morning, when the sun is about to come up.", match: ["dawn"] },
  { word: "Vision", meaning: "Something God lets a person see that others usually cannot see.", match: ["visions", "vision"] },
  { word: "Nonsense", meaning: "Words that do not make sense, or seem silly or untrue.", match: ["nonsense"] },
  { word: "Redeem", meaning: "To buy back or set free. God redeems people by rescuing them.", match: ["redeemed", "redeems", "redeem"] },
  { word: "Scriptures", meaning: "The holy writings of God's people. In this story, Israel's Scriptures, which Christians call the Old Testament.", match: ["Scriptures", "Scripture"] },
  { word: "Recognize", meaning: "To see someone and know who they are.", match: ["recognizing", "recognized", "recognize"] },
  { word: "Word and Sacrament", meaning: "The two ways Lutherans say Jesus comes to us: in God's word, and in Baptism and the Lord's Supper.", match: ["Word and Sacrament"] },
  { word: "Shepherd", meaning: "A person who takes care of sheep. The Bible often uses it as a picture of someone who cares for people.", match: ["shepherds", "shepherd"] },
  { word: "Charcoal fire", meaning: "A fire of glowing coals, good for cooking. John mentions one only twice: where Peter denied Jesus, and where Jesus fed him.", match: ["charcoal fire", "charcoal"] },
  { word: "Garment", meaning: "A piece of clothing. An outer garment is a coat or robe worn over other clothes.", match: ["garments", "garment"] },
  { word: "Tiberias", meaning: "A city on the Sea of Galilee. The lake is sometimes called the Sea of Tiberias.", match: ["Tiberias"] },
  { word: "Midwife", meaning: "A woman whose job is to help mothers give birth.", match: ["midwives", "midwife"] },
  { word: "Taskmaster", meaning: "A boss who forces slaves or workers to work hard.", match: ["taskmasters", "taskmaster"] },
  { word: "Papyrus", meaning: "A tall reed that grows by rivers in Egypt. People made baskets, boats, and paper from it.", match: ["papyrus"] },
  { word: "Pitch", meaning: "A thick, sticky black tar. It was spread on boats and baskets to keep water out.", match: ["pitch"] },
  { word: "Affliction", meaning: "Great suffering or trouble.", match: ["affliction"] },
  { word: "Staff", meaning: "A long, strong walking stick. Shepherds used one to guide their sheep.", match: ["staffs", "staff"] },
  { word: "Firstborn", meaning: "The oldest child in a family. In Bible times, the firstborn son had a special place.", match: ["firstborn"] },
  { word: "Elders", meaning: "The older leaders of a family, town, or people.", match: ["elders"] },
  { word: "Hardened heart", meaning: "A comparison for someone who will not change or listen, no matter what happens.", match: ["hardened Pharaoh's heart", "hardened their hearts", "hardened his heart", "heart stayed hard"] },
  { word: "Yoke", meaning: "A heavy wooden bar put on work animals. The Bible uses it as a picture of slavery or a heavy load.", match: ["yoke"] },
  { word: "Locusts", meaning: "A kind of grasshopper that flies in huge swarms and eats every green plant.", match: ["locusts", "locust"] },
  { word: "Goshen", meaning: "The part of Egypt where the Israelites lived. It was good land for flocks.", match: ["Goshen"] },
  { word: "Hyssop", meaning: "A small, bushy plant. People used it like a brush to sprinkle or spread liquids.", match: ["hyssop"] },
  { word: "Memorial", meaning: "Something that helps people remember an important event.", match: ["memorial"] },
  { word: "Vigil", meaning: "A night of staying awake to watch and pray.", match: ["vigil"] },
  { word: "Bitter herbs", meaning: "Plants with a sharp, bitter taste. In Jewish tradition, they help people remember how bitter slavery was.", match: ["bitter herbs"] },
  { word: "Chariot", meaning: "A light cart pulled by horses and used in war.", match: ["chariots", "chariot"] },
  { word: "Pillar of cloud", meaning: "A tall column of cloud. God led Israel in it by day, and in a pillar of fire by night.", match: ["pillar of cloud", "pillar of fire"] },
  { word: "Exalted", meaning: "Lifted high. Honored above everyone else.", match: ["exalted"] },
  { word: "Tambourine", meaning: "A small hand drum with jingles, shaken or tapped while people sing and dance.", match: ["tambourines", "tambourine"] },
  { word: "Savor", meaning: "Taste or flavor. Salt that loses its savor no longer tastes like salt.", match: ["savor", "Savor"] },
  { word: "Abolish", meaning: "To get rid of something completely. Jesus said he did not come to abolish God's law.", match: ["abolish", "Abolish"] },
  { word: "Fulfill", meaning: "To fill full. Jesus does everything the Law asks and brings about everything the Prophets promised.", match: ["fulfilled", "fulfills", "fulfill", "Fulfill"] },
  { word: "Jot", meaning: "The smallest letter in the alphabet. Jesus used it to say every part of God's word matters.", match: ["jot", "Jot"] },
  { word: "Enemy", meaning: "Someone who is against you or tries to hurt you. Loving an enemy does not mean trusting them.", match: ["enemies", "Enemies", "enemy", "Enemy"] },
  { word: "Revenge", meaning: "Hurting someone back because they hurt you. Getting even.", match: ["revenge", "Revenge"] },
  { word: "Tunic", meaning: "A long shirt worn under other clothes in Bible times.", match: ["tunic", "Tunic"] },
  { word: "Cloak", meaning: "A warm outer coat. Poor people often slept in it at night.", match: ["cloak", "Cloak"] },
  { word: "Anxiety", meaning: "A strong feeling of worry or fear, often about what might happen. It is a feeling, not a sin. For some people it lasts a long time, and doctors and counselors can help.", match: ["anxiety", "anxious"] },
  { word: "Mammon", meaning: "An old word for money or riches. Older Bibles use it in Matthew 6:24.", match: ["mammon"] },
  { word: "Solomon", meaning: "King David's son, who became king of Israel after him. He was famous for his riches and wisdom.", match: ["Solomon"] },
  { word: "Master", meaning: "Someone in charge, like a boss. People also called Jesus \"Master\" as a title of respect, like Teacher.", match: ["masters", "master"] },
  { word: "Essence", meaning: "The heart of something. Its most important part.", match: ["essence", "Essence"] },
  { word: "Swine", meaning: "An old word for pigs.", match: ["swine", "Swine"] },
  { word: "Speck", meaning: "A tiny bit of dust or dirt.", match: ["speck", "Speck"] },
  { word: "Golden Rule", meaning: "A name for Jesus's words \"Do to others as you would have them do to you\" (Matthew 7:12).", match: ["Golden Rule", "golden rule"] },
  { word: "Foundation", meaning: "The solid base a building sits on. It holds the building up.", match: ["foundations", "foundation", "Foundation"] },
  { word: "Torrent", meaning: "A rushing flood of water, like a stream after heavy rain.", match: ["torrents", "torrent", "Torrent"] },
  { word: "Authority", meaning: "The right to say what is true and what should be done.", match: ["authority", "Authority"] },
  { word: "Lawlessness", meaning: "Ignoring God's law and living as if it does not matter.", match: ["lawlessness", "Lawlessness"] },
  { word: "Offering", meaning: "A gift given to God.", match: ["offerings", "offering"] },
  { word: "Countenance", meaning: "A person's face, and the look on it.", match: ["countenance"] },
  { word: "Fugitive", meaning: "Someone who is always on the run and has no settled home.", match: ["fugitives", "fugitive"] },
  { word: "Murder", meaning: "Killing a person on purpose, when it is wrong to do so.", match: ["murders", "murder"] },
  { word: "Mortar", meaning: "A paste that holds building stones or bricks together.", match: ["mortar", "Mortar"] },
  { word: "Bitumen", meaning: "A thick, black, natural tar. People used it like glue for bricks.", match: ["bitumen", "Bitumen"] },
  { word: "Ziggurat", meaning: "A tall temple tower built in steps, like giant stairs. People in ancient Babylonia built them.", match: ["ziggurats", "Ziggurats", "ziggurat", "Ziggurat"] },
  { word: "Scattered", meaning: "Spread out in many directions, far apart.", match: ["scattered", "Scattered", "scatter"] },
  { word: "Heir", meaning: "The person who receives someone's things and land after they die.", match: ["heirs", "heir"] },
  { word: "Offspring", meaning: "A person's children, and the family that comes after them.", match: ["offspring"] },
  { word: "Credited", meaning: "Counted toward someone, like money written into their account. God counted Abram's trust as righteousness.", match: ["credited"] },
  { word: "Barren", meaning: "Unable to have a baby. In Bible times, this was a great sorrow for a family.", match: ["barren"] },
  { word: "Maidservant", meaning: "A woman servant. Hagar was an enslaved maidservant, owned by Sarai.", match: ["maidservants", "maidservant"] },
  { word: "Mistress", meaning: "In the Bible, a woman in charge of servants or slaves.", match: ["mistress"] },
  { word: "Contempt", meaning: "Treating someone as if they don't matter. Scorn.", match: ["contempt"] },
  { word: "Thicket", meaning: "A thick tangle of bushes or small trees.", match: ["thickets", "thicket"] },
  { word: "Ram", meaning: "A grown male sheep, with curled horns.", match: ["rams", "ram"] },
  { word: "Akedah", meaning: "A Hebrew word that means \"the binding.\" It is the Jewish name for this story, when Abraham tied up Isaac.", match: ["akedah"] },
  { word: "Birthright", meaning: "The special right of the firstborn son. He got a double share of his father's things and led the family.", match: ["birthright", "Birthright"] },
  { word: "Deceiver", meaning: "Someone who tricks people on purpose.", match: ["deceitfully", "deceiver", "Deceiver", "deceives", "deceit"] },
  { word: "Grudge", meaning: "Anger you keep holding on to for a long time.", match: ["grudge", "Grudge"] },
  { word: "Ark of the covenant", meaning: "A wooden chest covered with gold. It held the stone tablets of God's law and showed that God was with his people.", match: ["ark of the covenant", "ark of the LORD"] },
  { word: "Ram's horn", meaning: "An animal's horn, hollowed out and blown like a trumpet. In Hebrew it is called a shofar.", match: ["rams' horns", "ram's horns", "ram's horn", "rams' horn"] },
  { word: "Scarlet", meaning: "A bright red color.", match: ["scarlet"] },
  { word: "Devoted to destruction", meaning: "Given over wholly to God, so that nothing could be kept. In Hebrew it is one word, herem.", match: ["devoted to the LORD for destruction", "devoted to destruction"] },
  { word: "Nazirite", meaning: "A person set apart to God by a special promise. Nazirites did not cut their hair or drink wine.", match: ["Nazirites", "Nazirite"] },
  { word: "Judge", meaning: "Someone who decides what is right and fair. In the book of Judges, a judge was a leader God raised up to rescue Israel.", match: ["judged", "judge"] },
  { word: "Dagon", meaning: "The main god of the Philistines.", match: ["Dagon"] },
  { word: "Loom", meaning: "A wooden frame for weaving thread into cloth.", match: ["loom"] },
  { word: "Blaspheme", meaning: "To speak or act with disrespect toward God.", match: ["blasphemed", "blaspheme", "Blaspheme", "blasphemy"] },
  { word: "Iniquity", meaning: "Sin. Doing what is wrong in God's eyes.", match: ["iniquity", "Iniquity"] },
  { word: "Atone", meaning: "To make things right with God after a wrong. Christians believe Jesus's death does this for us.", match: ["atoning", "atoned", "atone", "Atone"] },
  { word: "Ephod", meaning: "A linen garment worn by priests and others serving God in Israel.", match: ["ephod", "Ephod"] },
  { word: "Baal", meaning: "The name means \"lord\" or \"master.\" Baal was the main god of the Canaanites and Phoenicians, the peoples around Israel.", match: ["Baals", "Baal"] },
  { word: "Asherah", meaning: "A goddess people worshiped along with Baal.", match: ["Asherah"] },
  { word: "Drought", meaning: "A long time with no rain.", match: ["drought", "Drought"] },
  { word: "Broom tree", meaning: "A desert bush with thin branches. Older Bibles call it a juniper.", match: ["broom tree", "Broom tree", "Broom Tree"] },
  { word: "Scepter", meaning: "A rod a king holds to show his power. In this story, holding it out meant a visitor could live.", match: ["scepter", "Scepter"] },
  { word: "Harem", meaning: "The part of a king's palace where the king's women lived.", match: ["harem", "Harem"] },
  { word: "Gallows", meaning: "A tall wooden frame used to hang a person. Some scholars think Haman's was a tall pole.", match: ["gallows", "Gallows"] },
  { word: "Purim", meaning: "A joyful Jewish holiday that remembers the rescue in the book of Esther. It comes from Pur, a word for the lot Haman cast.", match: ["Purim"] },
  { word: "Pledged", meaning: "Formally promised to marry. The wedding came later, but the promise was serious.", match: ["pledged", "pledge"] },
  { word: "Virgin", meaning: "Someone who has never had sex.", match: ["virgin"] },
  { word: "Most High", meaning: "A name for God. It means God is above everything.", match: ["Most High"] },
  { word: "Magnificat", meaning: "Mary's song of praise in Luke 1:46-55. The name is its first word in Latin.", match: ["Magnificat"] },
  { word: "Immanuel", meaning: "A Hebrew name that means \"God with us.\"", match: ["Immanuel"] },
  { word: "Almah", meaning: "A Hebrew word for a young woman of age to marry. Isaiah used it in Isaiah 7:14.", match: ["almah"] },
  { word: "Sadducees", meaning: "A Jewish group in Jesus's time. The high priest's circle belonged to it. They did not believe the dead would rise.", match: ["Sadducees", "Sadducee"] },
  { word: "Wilderness", meaning: "Dry, empty land where few people live. In the Bible, it is often a place where God meets people.", match: ["wilderness", "Wilderness"] },
  { word: "Confess", meaning: "To say out loud what you did wrong, to God or to others.", match: ["confessing", "Confessing", "confessed", "confess"] },
  { word: "Chaff", meaning: "The dry, light husks around grain. Farmers let the wind blow it away and kept the grain.", match: ["chaff", "Chaff"] },
  { word: "Gennesaret", meaning: "Another name for the Sea of Galilee. It came from a town and a green plain on the lake's western shore.", match: ["Gennesaret"] },
  { word: "Astonished", meaning: "So surprised you can hardly believe it.", match: ["astonished"] },
  { word: "Signaled", meaning: "Waved or made a sign to get someone's attention.", match: ["signaled"] },
  { word: "Paralyzed", meaning: "Not able to move some parts of the body. An old word for a person who is paralyzed is \"paralytic.\"", match: ["paralyzed", "paralytic", "paralysis"] },
  { word: "Capernaum", meaning: "A fishing town on the Sea of Galilee. Jesus lived there during much of his work.", match: ["Capernaum"] },
  { word: "Forgive", meaning: "To let go of a wrong someone did, instead of holding it against them. Only God can forgive sins against God.", match: ["forgiveness", "forgiven", "forgives", "forgive", "forgave"] },
  { word: "Talitha koum", meaning: "Aramaic words Jesus spoke to the girl. They mean \"Little girl, get up.\"", match: ["Talitha koum"] },
  { word: "Aramaic", meaning: "The everyday language Jesus and many Jewish people spoke in his time.", match: ["Aramaic"] },
  { word: "Commotion", meaning: "A lot of loud noise and movement from many people.", match: ["commotion"] },
  { word: "Grumble", meaning: "To complain in a low, unhappy voice.", match: ["grumbling", "grumblers", "grumbled", "grumble"] },
  { word: "Rejoice", meaning: "To be glad and celebrate.", match: ["rejoicing", "rejoices", "rejoiced", "rejoice"] },
  { word: "Sinner", meaning: "Someone who does wrong against God. In the Gospels, it often means people others looked down on for how they lived.", match: ["sinners", "sinner"] },
  { word: "Drachma", meaning: "A Greek silver coin in Bible times. It was worth about a day's pay.", match: ["drachmas", "drachma"] },
  { word: "Hosanna", meaning: "A Hebrew word that first meant \"Save us, please.\" People also shouted it as praise.", match: ["hosannas", "Hosanna", "hosanna"] },
  { word: "Colt", meaning: "A young donkey or horse.", match: ["colt", "Colt"] },
  { word: "Money changers", meaning: "People at tables in the temple who traded other money for the coins used to pay the temple tax.", match: ["money changers", "Money changers", "money changer"] },
  { word: "Temple", meaning: "God's house in Jerusalem, the center of Jewish worship. People came there to pray and bring offerings.", match: ["temple", "Temple"] },
  { word: "Talent", meaning: "In the Bible, a talent is a huge amount of money, about 20 years of a worker's pay. Today the word also means a skill, a meaning that grew mostly out of this parable.", match: ["talents", "talent"] },
  { word: "Interest", meaning: "Extra money paid back for the use of money. Bankers paid interest on money left with them.", match: ["interest"] },
  { word: "Outer darkness", meaning: "Picture language Jesus uses for being shut out, far from the light and joy of God's house.", match: ["outer darkness"] },
  { word: "Gnash", meaning: "To grind your teeth together. People do it in deep pain, grief, or anger.", match: ["gnashing", "gnash"] },
  { word: "Throne", meaning: "The special seat of a king. Sitting on it shows the king is ruling.", match: ["thrones", "throne"] },
  { word: "Nations", meaning: "Peoples and countries. In the Bible, \"all the nations\" means every people on earth.", match: ["nations"] },
  { word: "Cursed", meaning: "The opposite of blessed. Cut off from God's favor.", match: ["cursed"] },
  { word: "Minister", meaning: "To serve someone and take care of their needs.", match: ["minister"] },
  { word: "Rabboni", meaning: "A word that means \"my teacher.\" Mary used it for Jesus.", match: ["Rabboni", "rabboni"] },
  { word: "Ascend", meaning: "To go up. Jesus spoke of going up to his Father.", match: ["ascending", "ascended", "ascend", "Ascend"] },
  { word: "Magdala", meaning: "A town on the west shore of the Sea of Galilee. \"Magdalene\" means \"from Magdala.\"", match: ["Magdala"] },
  { word: "Demons", meaning: "Evil spirits. The Bible says Jesus set Mary free from seven of them.", match: ["demons", "Demons", "demon"] },
  { word: "Didymus", meaning: "A Greek word that means \"twin.\" It was another name for Thomas.", match: ["Didymus"] },
  { word: "Doubt", meaning: "Not being sure something is true. Honest questions are not the opposite of faith.", match: ["doubting", "Doubting", "doubts", "doubt", "Doubt"] },
  { word: "Office of the Keys", meaning: "The Lutheran name for the work Jesus gave his church: speaking God's forgiveness to people (John 20:22-23).", match: ["Office of the Keys"] },
  { word: "Damascus", meaning: "A very old city in Syria, about 133 miles north of Jerusalem. It is still a big city today.", match: ["Damascus"] },
  { word: "Tarsus", meaning: "Saul's home city. It was the main city of Cilicia, in what is now southern Turkey.", match: ["Tarsus"] },
  { word: "The Way", meaning: "An early name for the followers of Jesus, before they were called Christians.", match: ["the Way"] },
  { word: "Zealous", meaning: "Burning with devotion to something. Saul was zealous for God's law.", match: ["zealous"] },
  { word: "Agape", meaning: "A Greek word for love. In this chapter it means a love that gives and looks for the other person's good.", match: ["agape", "Agape"] },
  { word: "Cymbal", meaning: "A round metal plate that makes a loud crash when you hit it.", match: ["cymbal", "Cymbal"] },
  { word: "Prophecy", meaning: "Speaking a message from God.", match: ["Prophecy", "prophecy", "prophesy"] },
  { word: "Tongues", meaning: "Languages. Speaking in tongues is a gift of the Holy Spirit to speak or pray in a language the speaker did not learn. In Corinth, it needed someone to interpret it for the church (14:27).", match: ["tongues", "Tongues"] },
];
