/* The Word Bank. One plain meaning per word, used the same way in every
   story (Style Guide v1.1, Part 12). Word help underlines the first time
   a word appears in a story. Tapping it shows this meaning.

   Keep each meaning short: one or two sentences, common words only, so it
   works for young readers and for people still learning English.
   `match` lists the forms to look for in the text, longest first. */

export interface Word { word: string; meaning: string; match: string[] }

export const WORDS: Word[] = [
  { word: "Blessed", meaning: "God's favor rests on them.", match: ["Blessed", "blessed"] },
  { word: "Kingdom of heaven", meaning: "God's rule. The way God runs things. Not only a place after death: it starts wherever Jesus is. Also called the kingdom of God.", match: ["kingdom of heaven", "kingdom of God", "God's kingdom"] },
  { word: "Righteousness", meaning: "Being right with God, and doing what is right and fair. God gives it through Jesus, and then we grow in doing right.", match: ["righteousness"] },
  { word: "Repent", meaning: "Turn back to God. God is the one who turns us.", match: ["Repent", "repent"] },
  { word: "Grace", meaning: "God's love and gifts that we don't earn.", match: ["grace"] },
  { word: "Gospel", meaning: "The good news of what God does for us in Jesus.", match: ["gospel"] },
  { word: "Inherit", meaning: "Receive something as a gift because of whose family you're in.", match: ["inherit"] },
  { word: "Meek", meaning: "Gentle. Not pushy, and not weak.", match: ["meek"] },
  { word: "Mourn", meaning: "Feel deep sadness, often after someone dies.", match: ["mourn"] },
  { word: "Mercy", meaning: "Kindness and help for someone who is hurting or has done wrong.", match: ["merciful", "mercy"] },
  { word: "Persecuted", meaning: "Hurt or treated badly again and again, often because of what you believe.", match: ["persecuted", "persecute"] },
  { word: "Peacemakers", meaning: "People who help others stop fighting.", match: ["peacemakers"] },
  { word: "Hypocrite", meaning: "A pretender. The Greek word meant a stage actor.", match: ["hypocrite"] },
  { word: "Scribes", meaning: "Teachers of Moses's law.", match: ["scribes"] },
  { word: "Pharisees", meaning: "A Jewish group devoted to carefully keeping God's law.", match: ["Pharisees"] },
  { word: "Synagogue", meaning: "A local meeting place for Jewish worship and study.", match: ["synagogues", "synagogue"] },
  { word: "Disciples", meaning: "Followers who learn from a teacher. Jesus's disciples followed him everywhere.", match: ["disciples"] },
  { word: "Prophet", meaning: "Someone God sends to speak God's message.", match: ["prophets", "prophet"] },
  { word: "Messiah", meaning: "The anointed one: the king God promised to send. In Greek, the word is Christ.", match: ["Messiah"] },
  { word: "LORD", meaning: "LORD in capital letters stands for God's personal name. Jewish readers traditionally don't say it aloud, out of respect.", match: ["LORD"] },
  { word: "LORD of Hosts", meaning: "The Lord of armies. God commands the armies of heaven.", match: ["LORD of Hosts"] },
  { word: "Anoint", meaning: "Pour oil on someone to show God has chosen them.", match: ["anointed", "anoint"] },
  { word: "Philistines", meaning: "A people who lived near the sea, west of Israel. They were often at war with Israel.", match: ["Philistines", "Philistine"] },
  { word: "Salvation", meaning: "Being rescued by God.", match: ["Salvation", "salvation"] },
  { word: "Eternal life", meaning: "Life with God that never ends.", match: ["eternal life"] },
  { word: "Parable", meaning: "A short story Jesus told to teach something. The people in it are made up, but the point is real.", match: ["parable"] },
  { word: "Samaritans", meaning: "People from Samaria, north of Jerusalem. Jewish people and Samaritans had distrusted each other for centuries.", match: ["Samaritans", "Samaritan"] },
  { word: "Levite", meaning: "A helper at God's temple, from the family of Levi.", match: ["Levites", "Levite"] },
  { word: "Tax collectors", meaning: "People who collected money for the Roman rulers. Many took extra for themselves, so people saw them as cheats.", match: ["tax collectors", "tax collector"] },
  { word: "Son of Man", meaning: "A name Jesus often used for himself.", match: ["Son of Man"] },
  { word: "Compassion", meaning: "Caring deeply about someone who hurts, enough to help.", match: ["compassionate", "compassion"] },
  { word: "Sackcloth", meaning: "Rough cloth people wore to show they were sorry or sad.", match: ["sackcloth"] },
  { word: "Crucify", meaning: "To nail someone to a wooden cross and leave them to die. It was one of Rome's cruelest punishments.", match: ["crucified", "crucify"] },
  { word: "Paradise", meaning: "Being with God.", match: ["Paradise"] },
  { word: "Apostles", meaning: "Jesus's closest followers, the ones he sent out to tell others about him.", match: ["apostles"] },
  { word: "Sabbath", meaning: "The weekly day of rest, from Friday sunset to Saturday sunset.", match: ["Sabbath"] },
  { word: "Sin", meaning: "Turning away from God and hurting others or ourselves. Also the broken part of us that keeps doing it.", match: ["sins", "sinful", "sin"] },
  { word: "Faith", meaning: "Trusting God. Faith is a gift God gives, not something we make ourselves.", match: ["faith"] },
  { word: "Savior", meaning: "Someone who rescues. Christians call Jesus the Savior.", match: ["Savior"] },
  { word: "Risen", meaning: "Raised from the dead. God raised Jesus to a new life that never ends.", match: ["risen"] },
  { word: "Baptism", meaning: "Being washed with water in God's name. In Baptism, God makes you his own child.", match: ["Baptism", "baptized"] },
  { word: "Holy Spirit", meaning: "God's Spirit, who gives faith, brings comfort, and helps us live as God's people.", match: ["Holy Spirit", "Spirit of the LORD"] },
  { word: "Law", meaning: "God's commands, given through Moses. They show us how to live and where we fall short.", match: ["Moses's law", "God's law"] },
  { word: "Cast lots", meaning: "Throwing marked stones or sticks to choose or decide something.", match: ["cast lots", "casting lots", "Casting lots"] },
  { word: "Circumcision", meaning: "A sign, done to Jewish baby boys, that they belong to God's people and his promise.", match: ["uncircumcised", "circumcised", "Circumcision", "circumcision"] },
  { word: "Cubit", meaning: "An old measure, about 18 inches: the length from your elbow to your fingertips.", match: ["cubits", "cubit"] },
  { word: "Lectionary", meaning: "A plan for which Bible passages churches read each Sunday.", match: ["Lectionary", "lectionary"] },
  { word: "Year A, B, C", meaning: "The Sunday reading plan repeats every three years. The years are called A, B, and C.", match: ["Year A", "Year B", "Year C"] },
  { word: "Epiphany", meaning: "A church season in January and February about Jesus being shown to the world.", match: ["Epiphany"] },
  { word: "ELCA", meaning: "The Evangelical Lutheran Church in America.", match: ["ELCA"] },
  { word: "Josephus", meaning: "A Jewish historian who wrote about 60 years after Jesus.", match: ["Josephus"] },
  { word: "Image of God", meaning: "Made to reflect God in a way nothing else does. The Bible says this is true of every person.", match: ["image of God", "God's image", "His own image"] },
  { word: "Eden", meaning: "The place where God planted the first garden.", match: ["Eden"] },
  { word: "Serpent", meaning: "An old word for a snake.", match: ["serpent"] },
  { word: "Cherubim", meaning: "Powerful heavenly beings who guard God's holy places.", match: ["cherubim"] },
  { word: "Trinity", meaning: "One God in three persons: the Father, the Son, and the Holy Spirit.", match: ["Trinity"] },
  { word: "Ash Wednesday", meaning: "The first day of Lent. Many churches mark a cross of ashes on people's foreheads.", match: ["Ash Wednesday"] },
  { word: "Lent", meaning: "The 40 days before Easter, a time to turn back to God.", match: ["Lent"] },
  { word: "Pharaoh", meaning: "The title for the king of Egypt.", match: ["Pharaoh"] },
  { word: "Passover", meaning: "The night God passed over the Israelites' homes and set them free. Jewish families still celebrate it every year.", match: ["Passover"] },
  { word: "Plague", meaning: "A disaster that hurts a whole land.", match: ["plagues", "plague"] },
  { word: "Israelites", meaning: "God's people, the family of Abraham, Isaac, and Jacob. Jacob was also called Israel.", match: ["Israelites"] },
  { word: "Hebrews", meaning: "Another name for the Israelites.", match: ["Hebrews", "Hebrew"] },
  { word: "Covenant", meaning: "A promise that binds two sides together. God makes covenants with his people and keeps them.", match: ["covenant"] },
  { word: "Holy", meaning: "Set apart for God.", match: ["Holy", "holy"] },
  { word: "Maundy Thursday", meaning: "The Thursday before Easter, when Christians remember Jesus's Last Supper.", match: ["Maundy Thursday"] },
  { word: "Pentecost", meaning: "A Jewish harvest festival, 50 days after Passover. Christians remember it as the day the Holy Spirit came.", match: ["Pentecost"] },
  { word: "Witness", meaning: "Someone who saw something happen and tells about it.", match: ["witnesses", "witness"] },
  { word: "Galileans", meaning: "People from Galilee, the area in northern Israel where Jesus grew up.", match: ["Galileans"] },
  { word: "Centurion", meaning: "A Roman army officer in charge of about 100 soldiers.", match: ["centurion"] },
];
